/* tslint:disable */
/* eslint-disable */
/**
 * DrawBridge API
 * DrawBridge backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AcceptInviteRequest
 */
export interface AcceptInviteRequest {
    /**
     * 
     * @type {string}
     * @memberof AcceptInviteRequest
     */
    invite_token: string;
    /**
     * 
     * @type {string}
     * @memberof AcceptInviteRequest
     */
    password: string;
}

/**
 * Check if a given object implements the AcceptInviteRequest interface.
 */
export function instanceOfAcceptInviteRequest(value: object): value is AcceptInviteRequest {
    if (!('invite_token' in value) || value['invite_token'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function AcceptInviteRequestFromJSON(json: any): AcceptInviteRequest {
    return AcceptInviteRequestFromJSONTyped(json, false);
}

export function AcceptInviteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AcceptInviteRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'invite_token': json['invite_token'],
        'password': json['password'],
    };
}

export function AcceptInviteRequestToJSON(json: any): AcceptInviteRequest {
    return AcceptInviteRequestToJSONTyped(json, false);
}

export function AcceptInviteRequestToJSONTyped(value?: AcceptInviteRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'invite_token': value['invite_token'],
        'password': value['password'],
    };
}

