/* tslint:disable */
/* eslint-disable */
/**
 * DrawBridge API
 * DrawBridge backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
    UserToJSONTyped,
} from './User';
import type { UserPersona } from './UserPersona';
import {
    UserPersonaFromJSON,
    UserPersonaFromJSONTyped,
    UserPersonaToJSON,
    UserPersonaToJSONTyped,
} from './UserPersona';

/**
 * 
 * @export
 * @interface AdminUserAuthorization
 */
export interface AdminUserAuthorization {
    /**
     * 
     * @type {User}
     * @memberof AdminUserAuthorization
     */
    user: User;
    /**
     * 
     * @type {string}
     * @memberof AdminUserAuthorization
     */
    tenant_id: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof AdminUserAuthorization
     */
    role_keys: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof AdminUserAuthorization
     */
    grant_permissions: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof AdminUserAuthorization
     */
    deny_permissions: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof AdminUserAuthorization
     */
    effective_permissions: Array<string>;
    /**
     * 
     * @type {Array<UserPersona>}
     * @memberof AdminUserAuthorization
     */
    available_personas: Array<UserPersona>;
    /**
     * 
     * @type {Array<string>}
     * @memberof AdminUserAuthorization
     */
    available_permissions: Array<string>;
}

/**
 * Check if a given object implements the AdminUserAuthorization interface.
 */
export function instanceOfAdminUserAuthorization(value: object): value is AdminUserAuthorization {
    if (!('user' in value) || value['user'] === undefined) return false;
    if (!('tenant_id' in value) || value['tenant_id'] === undefined) return false;
    if (!('role_keys' in value) || value['role_keys'] === undefined) return false;
    if (!('grant_permissions' in value) || value['grant_permissions'] === undefined) return false;
    if (!('deny_permissions' in value) || value['deny_permissions'] === undefined) return false;
    if (!('effective_permissions' in value) || value['effective_permissions'] === undefined) return false;
    if (!('available_personas' in value) || value['available_personas'] === undefined) return false;
    if (!('available_permissions' in value) || value['available_permissions'] === undefined) return false;
    return true;
}

export function AdminUserAuthorizationFromJSON(json: any): AdminUserAuthorization {
    return AdminUserAuthorizationFromJSONTyped(json, false);
}

export function AdminUserAuthorizationFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminUserAuthorization {
    if (json == null) {
        return json;
    }
    return {
        
        'user': UserFromJSON(json['user']),
        'tenant_id': json['tenant_id'],
        'role_keys': json['role_keys'],
        'grant_permissions': json['grant_permissions'],
        'deny_permissions': json['deny_permissions'],
        'effective_permissions': json['effective_permissions'],
        'available_personas': ((json['available_personas'] as Array<any>).map(UserPersonaFromJSON)),
        'available_permissions': json['available_permissions'],
    };
}

export function AdminUserAuthorizationToJSON(json: any): AdminUserAuthorization {
    return AdminUserAuthorizationToJSONTyped(json, false);
}

export function AdminUserAuthorizationToJSONTyped(value?: AdminUserAuthorization | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user': UserToJSON(value['user']),
        'tenant_id': value['tenant_id'],
        'role_keys': value['role_keys'],
        'grant_permissions': value['grant_permissions'],
        'deny_permissions': value['deny_permissions'],
        'effective_permissions': value['effective_permissions'],
        'available_personas': ((value['available_personas'] as Array<any>).map(UserPersonaToJSON)),
        'available_permissions': value['available_permissions'],
    };
}

