/* tslint:disable */
/* eslint-disable */
/**
 * DrawBridge API
 * DrawBridge backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuditEvent
 */
export interface AuditEvent {
    /**
     * 
     * @type {string}
     * @memberof AuditEvent
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof AuditEvent
     */
    actor_user_id: string;
    /**
     * 
     * @type {string}
     * @memberof AuditEvent
     */
    tenant_id: string;
    /**
     * 
     * @type {string}
     * @memberof AuditEvent
     */
    organization_id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AuditEvent
     */
    action: string;
    /**
     * 
     * @type {string}
     * @memberof AuditEvent
     */
    entity_type: string;
    /**
     * 
     * @type {string}
     * @memberof AuditEvent
     */
    entity_id?: string | null;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof AuditEvent
     */
    metadata?: { [key: string]: any; };
    /**
     * 
     * @type {Date}
     * @memberof AuditEvent
     */
    date_added: Date;
}

/**
 * Check if a given object implements the AuditEvent interface.
 */
export function instanceOfAuditEvent(value: object): value is AuditEvent {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('actor_user_id' in value) || value['actor_user_id'] === undefined) return false;
    if (!('tenant_id' in value) || value['tenant_id'] === undefined) return false;
    if (!('action' in value) || value['action'] === undefined) return false;
    if (!('entity_type' in value) || value['entity_type'] === undefined) return false;
    if (!('date_added' in value) || value['date_added'] === undefined) return false;
    return true;
}

export function AuditEventFromJSON(json: any): AuditEvent {
    return AuditEventFromJSONTyped(json, false);
}

export function AuditEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuditEvent {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'actor_user_id': json['actor_user_id'],
        'tenant_id': json['tenant_id'],
        'organization_id': json['organization_id'] == null ? undefined : json['organization_id'],
        'action': json['action'],
        'entity_type': json['entity_type'],
        'entity_id': json['entity_id'] == null ? undefined : json['entity_id'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'date_added': (new Date(json['date_added'])),
    };
}

export function AuditEventToJSON(json: any): AuditEvent {
    return AuditEventToJSONTyped(json, false);
}

export function AuditEventToJSONTyped(value?: AuditEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'actor_user_id': value['actor_user_id'],
        'tenant_id': value['tenant_id'],
        'organization_id': value['organization_id'],
        'action': value['action'],
        'entity_type': value['entity_type'],
        'entity_id': value['entity_id'],
        'metadata': value['metadata'],
        'date_added': value['date_added'].toISOString(),
    };
}

