/* tslint:disable */
/* eslint-disable */
/**
 * DrawBridge API
 * DrawBridge backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BuildInfo
 */
export interface BuildInfo {
    /**
     * 
     * @type {string}
     * @memberof BuildInfo
     */
    version: string;
    /**
     * 
     * @type {string}
     * @memberof BuildInfo
     */
    commit: string;
    /**
     * 
     * @type {string}
     * @memberof BuildInfo
     */
    build_date: string;
}

/**
 * Check if a given object implements the BuildInfo interface.
 */
export function instanceOfBuildInfo(value: object): value is BuildInfo {
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('commit' in value) || value['commit'] === undefined) return false;
    if (!('build_date' in value) || value['build_date'] === undefined) return false;
    return true;
}

export function BuildInfoFromJSON(json: any): BuildInfo {
    return BuildInfoFromJSONTyped(json, false);
}

export function BuildInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BuildInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'version': json['version'],
        'commit': json['commit'],
        'build_date': json['build_date'],
    };
}

export function BuildInfoToJSON(json: any): BuildInfo {
    return BuildInfoToJSONTyped(json, false);
}

export function BuildInfoToJSONTyped(value?: BuildInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'version': value['version'],
        'commit': value['commit'],
        'build_date': value['build_date'],
    };
}

