/* tslint:disable */
/* eslint-disable */
/**
 * DrawBridge API
 * DrawBridge backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const CalendarManageScope = {
    None: 'none',
    Self: 'self',
    Organization: 'organization'
} as const;
export type CalendarManageScope = typeof CalendarManageScope[keyof typeof CalendarManageScope];


export function instanceOfCalendarManageScope(value: any): boolean {
    for (const key in CalendarManageScope) {
        if (Object.prototype.hasOwnProperty.call(CalendarManageScope, key)) {
            if (CalendarManageScope[key as keyof typeof CalendarManageScope] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CalendarManageScopeFromJSON(json: any): CalendarManageScope {
    return CalendarManageScopeFromJSONTyped(json, false);
}

export function CalendarManageScopeFromJSONTyped(json: any, ignoreDiscriminator: boolean): CalendarManageScope {
    return json as CalendarManageScope;
}

export function CalendarManageScopeToJSON(value?: CalendarManageScope | null): any {
    return value as any;
}

export function CalendarManageScopeToJSONTyped(value: any, ignoreDiscriminator: boolean): CalendarManageScope {
    return value as CalendarManageScope;
}

