/* tslint:disable */
/* eslint-disable */
/**
 * DrawBridge API
 * DrawBridge backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const CalendarSourceType = {
    Webinar: 'webinar',
    Qna: 'qna',
    Training: 'training'
} as const;
export type CalendarSourceType = typeof CalendarSourceType[keyof typeof CalendarSourceType];


export function instanceOfCalendarSourceType(value: any): boolean {
    for (const key in CalendarSourceType) {
        if (Object.prototype.hasOwnProperty.call(CalendarSourceType, key)) {
            if (CalendarSourceType[key as keyof typeof CalendarSourceType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CalendarSourceTypeFromJSON(json: any): CalendarSourceType {
    return CalendarSourceTypeFromJSONTyped(json, false);
}

export function CalendarSourceTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): CalendarSourceType {
    return json as CalendarSourceType;
}

export function CalendarSourceTypeToJSON(value?: CalendarSourceType | null): any {
    return value as any;
}

export function CalendarSourceTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): CalendarSourceType {
    return value as CalendarSourceType;
}

