/* tslint:disable */
/* eslint-disable */
/**
 * DrawBridge API
 * DrawBridge backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CallerContext
 */
export interface CallerContext {
    /**
     * 
     * @type {string}
     * @memberof CallerContext
     */
    subject: string;
    /**
     * 
     * @type {string}
     * @memberof CallerContext
     */
    tenant_id: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CallerContext
     */
    roles: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof CallerContext
     */
    permissions: Array<string>;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof CallerContext
     */
    claims?: { [key: string]: any; };
}

/**
 * Check if a given object implements the CallerContext interface.
 */
export function instanceOfCallerContext(value: object): value is CallerContext {
    if (!('subject' in value) || value['subject'] === undefined) return false;
    if (!('tenant_id' in value) || value['tenant_id'] === undefined) return false;
    if (!('roles' in value) || value['roles'] === undefined) return false;
    if (!('permissions' in value) || value['permissions'] === undefined) return false;
    return true;
}

export function CallerContextFromJSON(json: any): CallerContext {
    return CallerContextFromJSONTyped(json, false);
}

export function CallerContextFromJSONTyped(json: any, ignoreDiscriminator: boolean): CallerContext {
    if (json == null) {
        return json;
    }
    return {
        
        'subject': json['subject'],
        'tenant_id': json['tenant_id'],
        'roles': json['roles'],
        'permissions': json['permissions'],
        'claims': json['claims'] == null ? undefined : json['claims'],
    };
}

export function CallerContextToJSON(json: any): CallerContext {
    return CallerContextToJSONTyped(json, false);
}

export function CallerContextToJSONTyped(value?: CallerContext | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'subject': value['subject'],
        'tenant_id': value['tenant_id'],
        'roles': value['roles'],
        'permissions': value['permissions'],
        'claims': value['claims'],
    };
}

