/* tslint:disable */
/* eslint-disable */
/**
 * DrawBridge API
 * DrawBridge backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const CatalogContentType = {
    Ifu: 'ifu',
    Guide: 'guide',
    Video: 'video',
    Regulatory: 'regulatory'
} as const;
export type CatalogContentType = typeof CatalogContentType[keyof typeof CatalogContentType];


export function instanceOfCatalogContentType(value: any): boolean {
    for (const key in CatalogContentType) {
        if (Object.prototype.hasOwnProperty.call(CatalogContentType, key)) {
            if (CatalogContentType[key as keyof typeof CatalogContentType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CatalogContentTypeFromJSON(json: any): CatalogContentType {
    return CatalogContentTypeFromJSONTyped(json, false);
}

export function CatalogContentTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): CatalogContentType {
    return json as CatalogContentType;
}

export function CatalogContentTypeToJSON(value?: CatalogContentType | null): any {
    return value as any;
}

export function CatalogContentTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): CatalogContentType {
    return value as CatalogContentType;
}

