/* tslint:disable */
/* eslint-disable */
/**
 * DrawBridge API
 * DrawBridge backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CatalogContentType } from './CatalogContentType';
import {
    CatalogContentTypeFromJSON,
    CatalogContentTypeFromJSONTyped,
    CatalogContentTypeToJSON,
    CatalogContentTypeToJSONTyped,
} from './CatalogContentType';
import type { CatalogContentStatus } from './CatalogContentStatus';
import {
    CatalogContentStatusFromJSON,
    CatalogContentStatusFromJSONTyped,
    CatalogContentStatusToJSON,
    CatalogContentStatusToJSONTyped,
} from './CatalogContentStatus';

/**
 * 
 * @export
 * @interface CatalogContentItem
 */
export interface CatalogContentItem {
    /**
     * 
     * @type {string}
     * @memberof CatalogContentItem
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CatalogContentItem
     */
    organization_id: string;
    /**
     * 
     * @type {string}
     * @memberof CatalogContentItem
     */
    product_id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CatalogContentItem
     */
    created_by_user_id: string;
    /**
     * 
     * @type {string}
     * @memberof CatalogContentItem
     */
    updated_by_user_id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CatalogContentItem
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof CatalogContentItem
     */
    description?: string;
    /**
     * 
     * @type {CatalogContentType}
     * @memberof CatalogContentItem
     */
    content_type: CatalogContentType;
    /**
     * 
     * @type {string}
     * @memberof CatalogContentItem
     */
    external_url: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CatalogContentItem
     */
    tags: Array<string>;
    /**
     * 
     * @type {CatalogContentStatus}
     * @memberof CatalogContentItem
     */
    status: CatalogContentStatus;
    /**
     * 
     * @type {Date}
     * @memberof CatalogContentItem
     */
    date_added: Date;
    /**
     * 
     * @type {Date}
     * @memberof CatalogContentItem
     */
    date_updated?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof CatalogContentItem
     */
    date_archived?: Date | null;
}



/**
 * Check if a given object implements the CatalogContentItem interface.
 */
export function instanceOfCatalogContentItem(value: object): value is CatalogContentItem {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('organization_id' in value) || value['organization_id'] === undefined) return false;
    if (!('created_by_user_id' in value) || value['created_by_user_id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('content_type' in value) || value['content_type'] === undefined) return false;
    if (!('external_url' in value) || value['external_url'] === undefined) return false;
    if (!('tags' in value) || value['tags'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('date_added' in value) || value['date_added'] === undefined) return false;
    return true;
}

export function CatalogContentItemFromJSON(json: any): CatalogContentItem {
    return CatalogContentItemFromJSONTyped(json, false);
}

export function CatalogContentItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): CatalogContentItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'organization_id': json['organization_id'],
        'product_id': json['product_id'] == null ? undefined : json['product_id'],
        'created_by_user_id': json['created_by_user_id'],
        'updated_by_user_id': json['updated_by_user_id'] == null ? undefined : json['updated_by_user_id'],
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'content_type': CatalogContentTypeFromJSON(json['content_type']),
        'external_url': json['external_url'],
        'tags': json['tags'],
        'status': CatalogContentStatusFromJSON(json['status']),
        'date_added': (new Date(json['date_added'])),
        'date_updated': json['date_updated'] == null ? undefined : (new Date(json['date_updated'])),
        'date_archived': json['date_archived'] == null ? undefined : (new Date(json['date_archived'])),
    };
}

export function CatalogContentItemToJSON(json: any): CatalogContentItem {
    return CatalogContentItemToJSONTyped(json, false);
}

export function CatalogContentItemToJSONTyped(value?: CatalogContentItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'organization_id': value['organization_id'],
        'product_id': value['product_id'],
        'created_by_user_id': value['created_by_user_id'],
        'updated_by_user_id': value['updated_by_user_id'],
        'title': value['title'],
        'description': value['description'],
        'content_type': CatalogContentTypeToJSON(value['content_type']),
        'external_url': value['external_url'],
        'tags': value['tags'],
        'status': CatalogContentStatusToJSON(value['status']),
        'date_added': value['date_added'].toISOString(),
        'date_updated': value['date_updated'] == null ? value['date_updated'] : value['date_updated'].toISOString(),
        'date_archived': value['date_archived'] == null ? value['date_archived'] : value['date_archived'].toISOString(),
    };
}

