/* tslint:disable */
/* eslint-disable */
/**
 * DrawBridge API
 * DrawBridge backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const CatalogContentStatus = {
    Active: 'active',
    Archived: 'archived'
} as const;
export type CatalogContentStatus = typeof CatalogContentStatus[keyof typeof CatalogContentStatus];


export function instanceOfCatalogContentStatus(value: any): boolean {
    for (const key in CatalogContentStatus) {
        if (Object.prototype.hasOwnProperty.call(CatalogContentStatus, key)) {
            if (CatalogContentStatus[key as keyof typeof CatalogContentStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CatalogContentStatusFromJSON(json: any): CatalogContentStatus {
    return CatalogContentStatusFromJSONTyped(json, false);
}

export function CatalogContentStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): CatalogContentStatus {
    return json as CatalogContentStatus;
}

export function CatalogContentStatusToJSON(value?: CatalogContentStatus | null): any {
    return value as any;
}

export function CatalogContentStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): CatalogContentStatus {
    return value as CatalogContentStatus;
}

