/* tslint:disable */
/* eslint-disable */
/**
 * DrawBridge API
 * DrawBridge backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateOrganizationRepRequest
 */
export interface CreateOrganizationRepRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateOrganizationRepRequest
     */
    user_id: string;
}

/**
 * Check if a given object implements the CreateOrganizationRepRequest interface.
 */
export function instanceOfCreateOrganizationRepRequest(value: object): value is CreateOrganizationRepRequest {
    if (!('user_id' in value) || value['user_id'] === undefined) return false;
    return true;
}

export function CreateOrganizationRepRequestFromJSON(json: any): CreateOrganizationRepRequest {
    return CreateOrganizationRepRequestFromJSONTyped(json, false);
}

export function CreateOrganizationRepRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOrganizationRepRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'user_id': json['user_id'],
    };
}

export function CreateOrganizationRepRequestToJSON(json: any): CreateOrganizationRepRequest {
    return CreateOrganizationRepRequestToJSONTyped(json, false);
}

export function CreateOrganizationRepRequestToJSONTyped(value?: CreateOrganizationRepRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user_id': value['user_id'],
    };
}

