/* tslint:disable */
/* eslint-disable */
/**
 * DrawBridge API
 * DrawBridge backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CatalogContentType } from './CatalogContentType';
import {
    CatalogContentTypeFromJSON,
    CatalogContentTypeFromJSONTyped,
    CatalogContentTypeToJSON,
    CatalogContentTypeToJSONTyped,
} from './CatalogContentType';

/**
 * 
 * @export
 * @interface CreateCatalogContentRequest
 */
export interface CreateCatalogContentRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateCatalogContentRequest
     */
    organization_id: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCatalogContentRequest
     */
    product_id?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCatalogContentRequest
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCatalogContentRequest
     */
    description?: string;
    /**
     * 
     * @type {CatalogContentType}
     * @memberof CreateCatalogContentRequest
     */
    content_type: CatalogContentType;
    /**
     * 
     * @type {string}
     * @memberof CreateCatalogContentRequest
     */
    external_url: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateCatalogContentRequest
     */
    tags?: Array<string>;
}



/**
 * Check if a given object implements the CreateCatalogContentRequest interface.
 */
export function instanceOfCreateCatalogContentRequest(value: object): value is CreateCatalogContentRequest {
    if (!('organization_id' in value) || value['organization_id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('content_type' in value) || value['content_type'] === undefined) return false;
    if (!('external_url' in value) || value['external_url'] === undefined) return false;
    return true;
}

export function CreateCatalogContentRequestFromJSON(json: any): CreateCatalogContentRequest {
    return CreateCatalogContentRequestFromJSONTyped(json, false);
}

export function CreateCatalogContentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCatalogContentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'organization_id': json['organization_id'],
        'product_id': json['product_id'] == null ? undefined : json['product_id'],
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'content_type': CatalogContentTypeFromJSON(json['content_type']),
        'external_url': json['external_url'],
        'tags': json['tags'] == null ? undefined : json['tags'],
    };
}

export function CreateCatalogContentRequestToJSON(json: any): CreateCatalogContentRequest {
    return CreateCatalogContentRequestToJSONTyped(json, false);
}

export function CreateCatalogContentRequestToJSONTyped(value?: CreateCatalogContentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'organization_id': value['organization_id'],
        'product_id': value['product_id'],
        'title': value['title'],
        'description': value['description'],
        'content_type': CatalogContentTypeToJSON(value['content_type']),
        'external_url': value['external_url'],
        'tags': value['tags'],
    };
}

