/* tslint:disable */
/* eslint-disable */
/**
 * DrawBridge API
 * DrawBridge backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateAdminUserRequest
 */
export interface CreateAdminUserRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateAdminUserRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof CreateAdminUserRequest
     */
    first_name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateAdminUserRequest
     */
    last_name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateAdminUserRequest
     */
    phone_number?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateAdminUserRequest
     */
    password: string;
}

/**
 * Check if a given object implements the CreateAdminUserRequest interface.
 */
export function instanceOfCreateAdminUserRequest(value: object): value is CreateAdminUserRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('first_name' in value) || value['first_name'] === undefined) return false;
    if (!('last_name' in value) || value['last_name'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function CreateAdminUserRequestFromJSON(json: any): CreateAdminUserRequest {
    return CreateAdminUserRequestFromJSONTyped(json, false);
}

export function CreateAdminUserRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAdminUserRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'first_name': json['first_name'],
        'last_name': json['last_name'],
        'phone_number': json['phone_number'] == null ? undefined : json['phone_number'],
        'password': json['password'],
    };
}

export function CreateAdminUserRequestToJSON(json: any): CreateAdminUserRequest {
    return CreateAdminUserRequestToJSONTyped(json, false);
}

export function CreateAdminUserRequestToJSONTyped(value?: CreateAdminUserRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'first_name': value['first_name'],
        'last_name': value['last_name'],
        'phone_number': value['phone_number'],
        'password': value['password'],
    };
}

