/* tslint:disable */
/* eslint-disable */
/**
 * DrawBridge API
 * DrawBridge backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateWebinarRequest
 */
export interface CreateWebinarRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateWebinarRequest
     */
    organization_id: string;
    /**
     * 
     * @type {string}
     * @memberof CreateWebinarRequest
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof CreateWebinarRequest
     */
    description?: string;
    /**
     * 
     * @type {Date}
     * @memberof CreateWebinarRequest
     */
    starts_at: Date;
    /**
     * 
     * @type {Date}
     * @memberof CreateWebinarRequest
     */
    ends_at: Date;
}

/**
 * Check if a given object implements the CreateWebinarRequest interface.
 */
export function instanceOfCreateWebinarRequest(value: object): value is CreateWebinarRequest {
    if (!('organization_id' in value) || value['organization_id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('starts_at' in value) || value['starts_at'] === undefined) return false;
    if (!('ends_at' in value) || value['ends_at'] === undefined) return false;
    return true;
}

export function CreateWebinarRequestFromJSON(json: any): CreateWebinarRequest {
    return CreateWebinarRequestFromJSONTyped(json, false);
}

export function CreateWebinarRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateWebinarRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'organization_id': json['organization_id'],
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'starts_at': (new Date(json['starts_at'])),
        'ends_at': (new Date(json['ends_at'])),
    };
}

export function CreateWebinarRequestToJSON(json: any): CreateWebinarRequest {
    return CreateWebinarRequestToJSONTyped(json, false);
}

export function CreateWebinarRequestToJSONTyped(value?: CreateWebinarRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'organization_id': value['organization_id'],
        'title': value['title'],
        'description': value['description'],
        'starts_at': value['starts_at'].toISOString(),
        'ends_at': value['ends_at'].toISOString(),
    };
}

