/* tslint:disable */
/* eslint-disable */
/**
 * MedBridge API
 * MedBridge backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CallerContext } from './CallerContext';
import {
    CallerContextFromJSON,
    CallerContextFromJSONTyped,
    CallerContextToJSON,
    CallerContextToJSONTyped,
} from './CallerContext';

/**
 * 
 * @export
 * @interface CreateSessionResponse
 */
export interface CreateSessionResponse {
    /**
     * 
     * @type {string}
     * @memberof CreateSessionResponse
     */
    access_token: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSessionResponse
     */
    token_type: string;
    /**
     * 
     * @type {number}
     * @memberof CreateSessionResponse
     */
    expires_in_seconds: number;
    /**
     * 
     * @type {CallerContext}
     * @memberof CreateSessionResponse
     */
    caller: CallerContext;
}

/**
 * Check if a given object implements the CreateSessionResponse interface.
 */
export function instanceOfCreateSessionResponse(value: object): value is CreateSessionResponse {
    if (!('access_token' in value) || value['access_token'] === undefined) return false;
    if (!('token_type' in value) || value['token_type'] === undefined) return false;
    if (!('expires_in_seconds' in value) || value['expires_in_seconds'] === undefined) return false;
    if (!('caller' in value) || value['caller'] === undefined) return false;
    return true;
}

export function CreateSessionResponseFromJSON(json: any): CreateSessionResponse {
    return CreateSessionResponseFromJSONTyped(json, false);
}

export function CreateSessionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSessionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'access_token': json['access_token'],
        'token_type': json['token_type'],
        'expires_in_seconds': json['expires_in_seconds'],
        'caller': CallerContextFromJSON(json['caller']),
    };
}

export function CreateSessionResponseToJSON(json: any): CreateSessionResponse {
    return CreateSessionResponseToJSONTyped(json, false);
}

export function CreateSessionResponseToJSONTyped(value?: CreateSessionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'access_token': value['access_token'],
        'token_type': value['token_type'],
        'expires_in_seconds': value['expires_in_seconds'],
        'caller': CallerContextToJSON(value['caller']),
    };
}

