/* tslint:disable */
/* eslint-disable */
/**
 * DrawBridge API
 * DrawBridge backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateOrganizationUserRequest
 */
export interface CreateOrganizationUserRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateOrganizationUserRequest
     */
    user_id: string;
}

/**
 * Check if a given object implements the CreateOrganizationUserRequest interface.
 */
export function instanceOfCreateOrganizationUserRequest(value: object): value is CreateOrganizationUserRequest {
    if (!('user_id' in value) || value['user_id'] === undefined) return false;
    return true;
}

export function CreateOrganizationUserRequestFromJSON(json: any): CreateOrganizationUserRequest {
    return CreateOrganizationUserRequestFromJSONTyped(json, false);
}

export function CreateOrganizationUserRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOrganizationUserRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'user_id': json['user_id'],
    };
}

export function CreateOrganizationUserRequestToJSON(json: any): CreateOrganizationUserRequest {
    return CreateOrganizationUserRequestToJSONTyped(json, false);
}

export function CreateOrganizationUserRequestToJSONTyped(value?: CreateOrganizationUserRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user_id': value['user_id'],
    };
}

