/* tslint:disable */
/* eslint-disable */
/**
 * MedBridge API
 * MedBridge backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateProductUserRequest
 */
export interface CreateProductUserRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateProductUserRequest
     */
    user_id: string;
}

/**
 * Check if a given object implements the CreateProductUserRequest interface.
 */
export function instanceOfCreateProductUserRequest(value: object): value is CreateProductUserRequest {
    if (!('user_id' in value) || value['user_id'] === undefined) return false;
    return true;
}

export function CreateProductUserRequestFromJSON(json: any): CreateProductUserRequest {
    return CreateProductUserRequestFromJSONTyped(json, false);
}

export function CreateProductUserRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateProductUserRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'user_id': json['user_id'],
    };
}

export function CreateProductUserRequestToJSON(json: any): CreateProductUserRequest {
    return CreateProductUserRequestToJSONTyped(json, false);
}

export function CreateProductUserRequestToJSONTyped(value?: CreateProductUserRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user_id': value['user_id'],
    };
}

