/* tslint:disable */
/* eslint-disable */
/**
 * MedBridge API
 * MedBridge backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateTrainingRequestRequest
 */
export interface CreateTrainingRequestRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateTrainingRequestRequest
     */
    hospital_organization_id: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTrainingRequestRequest
     */
    product_id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateTrainingRequestRequest
     */
    topic: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTrainingRequestRequest
     */
    notes?: string | null;
}

/**
 * Check if a given object implements the CreateTrainingRequestRequest interface.
 */
export function instanceOfCreateTrainingRequestRequest(value: object): value is CreateTrainingRequestRequest {
    if (!('hospital_organization_id' in value) || value['hospital_organization_id'] === undefined) return false;
    if (!('topic' in value) || value['topic'] === undefined) return false;
    return true;
}

export function CreateTrainingRequestRequestFromJSON(json: any): CreateTrainingRequestRequest {
    return CreateTrainingRequestRequestFromJSONTyped(json, false);
}

export function CreateTrainingRequestRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTrainingRequestRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'hospital_organization_id': json['hospital_organization_id'],
        'product_id': json['product_id'] == null ? undefined : json['product_id'],
        'topic': json['topic'],
        'notes': json['notes'] == null ? undefined : json['notes'],
    };
}

export function CreateTrainingRequestRequestToJSON(json: any): CreateTrainingRequestRequest {
    return CreateTrainingRequestRequestToJSONTyped(json, false);
}

export function CreateTrainingRequestRequestToJSONTyped(value?: CreateTrainingRequestRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'hospital_organization_id': value['hospital_organization_id'],
        'product_id': value['product_id'],
        'topic': value['topic'],
        'notes': value['notes'],
    };
}

