/* tslint:disable */
/* eslint-disable */
/**
 * MedBridge API
 * MedBridge backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrganizationRelationType } from './OrganizationRelationType';
import {
    OrganizationRelationTypeFromJSON,
    OrganizationRelationTypeFromJSONTyped,
    OrganizationRelationTypeToJSON,
    OrganizationRelationTypeToJSONTyped,
} from './OrganizationRelationType';

/**
 * 
 * @export
 * @interface CreateOrganizationRelationRequest
 */
export interface CreateOrganizationRelationRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateOrganizationRelationRequest
     */
    child_organization_id: string;
    /**
     * 
     * @type {OrganizationRelationType}
     * @memberof CreateOrganizationRelationRequest
     */
    relation_type: OrganizationRelationType;
}



/**
 * Check if a given object implements the CreateOrganizationRelationRequest interface.
 */
export function instanceOfCreateOrganizationRelationRequest(value: object): value is CreateOrganizationRelationRequest {
    if (!('child_organization_id' in value) || value['child_organization_id'] === undefined) return false;
    if (!('relation_type' in value) || value['relation_type'] === undefined) return false;
    return true;
}

export function CreateOrganizationRelationRequestFromJSON(json: any): CreateOrganizationRelationRequest {
    return CreateOrganizationRelationRequestFromJSONTyped(json, false);
}

export function CreateOrganizationRelationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOrganizationRelationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'child_organization_id': json['child_organization_id'],
        'relation_type': OrganizationRelationTypeFromJSON(json['relation_type']),
    };
}

export function CreateOrganizationRelationRequestToJSON(json: any): CreateOrganizationRelationRequest {
    return CreateOrganizationRelationRequestToJSONTyped(json, false);
}

export function CreateOrganizationRelationRequestToJSONTyped(value?: CreateOrganizationRelationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'child_organization_id': value['child_organization_id'],
        'relation_type': OrganizationRelationTypeToJSON(value['relation_type']),
    };
}

