/* tslint:disable */
/* eslint-disable */
/**
 * MedBridge API
 * MedBridge backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateRepCoverageRequest
 */
export interface CreateRepCoverageRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateRepCoverageRequest
     */
    rep_user_id: string;
    /**
     * 
     * @type {string}
     * @memberof CreateRepCoverageRequest
     */
    hospital_organization_id: string;
    /**
     * 
     * @type {string}
     * @memberof CreateRepCoverageRequest
     */
    product_id?: string | null;
}

/**
 * Check if a given object implements the CreateRepCoverageRequest interface.
 */
export function instanceOfCreateRepCoverageRequest(value: object): value is CreateRepCoverageRequest {
    if (!('rep_user_id' in value) || value['rep_user_id'] === undefined) return false;
    if (!('hospital_organization_id' in value) || value['hospital_organization_id'] === undefined) return false;
    return true;
}

export function CreateRepCoverageRequestFromJSON(json: any): CreateRepCoverageRequest {
    return CreateRepCoverageRequestFromJSONTyped(json, false);
}

export function CreateRepCoverageRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateRepCoverageRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'rep_user_id': json['rep_user_id'],
        'hospital_organization_id': json['hospital_organization_id'],
        'product_id': json['product_id'] == null ? undefined : json['product_id'],
    };
}

export function CreateRepCoverageRequestToJSON(json: any): CreateRepCoverageRequest {
    return CreateRepCoverageRequestToJSONTyped(json, false);
}

export function CreateRepCoverageRequestToJSONTyped(value?: CreateRepCoverageRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rep_user_id': value['rep_user_id'],
        'hospital_organization_id': value['hospital_organization_id'],
        'product_id': value['product_id'],
    };
}

