/* tslint:disable */
/* eslint-disable */
/**
 * MedBridge API
 * MedBridge backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MembershipStatus } from './MembershipStatus';
import {
    MembershipStatusFromJSON,
    MembershipStatusFromJSONTyped,
    MembershipStatusToJSON,
    MembershipStatusToJSONTyped,
} from './MembershipStatus';
import type { MembershipRole } from './MembershipRole';
import {
    MembershipRoleFromJSON,
    MembershipRoleFromJSONTyped,
    MembershipRoleToJSON,
    MembershipRoleToJSONTyped,
} from './MembershipRole';

/**
 * 
 * @export
 * @interface CreateMembershipRequest
 */
export interface CreateMembershipRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateMembershipRequest
     */
    user_id: string;
    /**
     * 
     * @type {MembershipRole}
     * @memberof CreateMembershipRequest
     */
    role: MembershipRole;
    /**
     * 
     * @type {MembershipStatus}
     * @memberof CreateMembershipRequest
     */
    membership_status?: MembershipStatus;
}



/**
 * Check if a given object implements the CreateMembershipRequest interface.
 */
export function instanceOfCreateMembershipRequest(value: object): value is CreateMembershipRequest {
    if (!('user_id' in value) || value['user_id'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    return true;
}

export function CreateMembershipRequestFromJSON(json: any): CreateMembershipRequest {
    return CreateMembershipRequestFromJSONTyped(json, false);
}

export function CreateMembershipRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateMembershipRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'user_id': json['user_id'],
        'role': MembershipRoleFromJSON(json['role']),
        'membership_status': json['membership_status'] == null ? undefined : MembershipStatusFromJSON(json['membership_status']),
    };
}

export function CreateMembershipRequestToJSON(json: any): CreateMembershipRequest {
    return CreateMembershipRequestToJSONTyped(json, false);
}

export function CreateMembershipRequestToJSONTyped(value?: CreateMembershipRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user_id': value['user_id'],
        'role': MembershipRoleToJSON(value['role']),
        'membership_status': MembershipStatusToJSON(value['membership_status']),
    };
}

