/* tslint:disable */
/* eslint-disable */
/**
 * DrawBridge API
 * DrawBridge backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateWebinarQnARequest
 */
export interface CreateWebinarQnARequest {
    /**
     * 
     * @type {string}
     * @memberof CreateWebinarQnARequest
     */
    question: string;
}

/**
 * Check if a given object implements the CreateWebinarQnARequest interface.
 */
export function instanceOfCreateWebinarQnARequest(value: object): value is CreateWebinarQnARequest {
    if (!('question' in value) || value['question'] === undefined) return false;
    return true;
}

export function CreateWebinarQnARequestFromJSON(json: any): CreateWebinarQnARequest {
    return CreateWebinarQnARequestFromJSONTyped(json, false);
}

export function CreateWebinarQnARequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateWebinarQnARequest {
    if (json == null) {
        return json;
    }
    return {
        
        'question': json['question'],
    };
}

export function CreateWebinarQnARequestToJSON(json: any): CreateWebinarQnARequest {
    return CreateWebinarQnARequestToJSONTyped(json, false);
}

export function CreateWebinarQnARequestToJSONTyped(value?: CreateWebinarQnARequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'question': value['question'],
    };
}

