/* tslint:disable */
/* eslint-disable */
/**
 * DrawBridge API
 * DrawBridge backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserPersona } from './UserPersona';
import {
    UserPersonaFromJSON,
    UserPersonaFromJSONTyped,
    UserPersonaToJSON,
    UserPersonaToJSONTyped,
} from './UserPersona';

/**
 * 
 * @export
 * @interface CreateInviteRequest
 */
export interface CreateInviteRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateInviteRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof CreateInviteRequest
     */
    first_name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateInviteRequest
     */
    last_name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateInviteRequest
     */
    phone_number?: string;
    /**
     * 
     * @type {UserPersona}
     * @memberof CreateInviteRequest
     */
    persona: UserPersona;
    /**
     * 
     * @type {string}
     * @memberof CreateInviteRequest
     */
    organization_id?: string;
    /**
     * 
     * @type {number}
     * @memberof CreateInviteRequest
     */
    expires_in_seconds?: number;
}



/**
 * Check if a given object implements the CreateInviteRequest interface.
 */
export function instanceOfCreateInviteRequest(value: object): value is CreateInviteRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('first_name' in value) || value['first_name'] === undefined) return false;
    if (!('last_name' in value) || value['last_name'] === undefined) return false;
    if (!('persona' in value) || value['persona'] === undefined) return false;
    return true;
}

export function CreateInviteRequestFromJSON(json: any): CreateInviteRequest {
    return CreateInviteRequestFromJSONTyped(json, false);
}

export function CreateInviteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateInviteRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'first_name': json['first_name'],
        'last_name': json['last_name'],
        'phone_number': json['phone_number'] == null ? undefined : json['phone_number'],
        'persona': UserPersonaFromJSON(json['persona']),
        'organization_id': json['organization_id'] == null ? undefined : json['organization_id'],
        'expires_in_seconds': json['expires_in_seconds'] == null ? undefined : json['expires_in_seconds'],
    };
}

export function CreateInviteRequestToJSON(json: any): CreateInviteRequest {
    return CreateInviteRequestToJSONTyped(json, false);
}

export function CreateInviteRequestToJSONTyped(value?: CreateInviteRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'first_name': value['first_name'],
        'last_name': value['last_name'],
        'phone_number': value['phone_number'],
        'persona': UserPersonaToJSON(value['persona']),
        'organization_id': value['organization_id'],
        'expires_in_seconds': value['expires_in_seconds'],
    };
}

