/* tslint:disable */
/* eslint-disable */
/**
 * MedBridge API
 * MedBridge backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Invite } from './Invite';
import {
    InviteFromJSON,
    InviteFromJSONTyped,
    InviteToJSON,
    InviteToJSONTyped,
} from './Invite';

/**
 * 
 * @export
 * @interface CreateInviteResponse
 */
export interface CreateInviteResponse {
    /**
     * 
     * @type {string}
     * @memberof CreateInviteResponse
     */
    invite_token: string;
    /**
     * 
     * @type {Invite}
     * @memberof CreateInviteResponse
     */
    invite: Invite;
}

/**
 * Check if a given object implements the CreateInviteResponse interface.
 */
export function instanceOfCreateInviteResponse(value: object): value is CreateInviteResponse {
    if (!('invite_token' in value) || value['invite_token'] === undefined) return false;
    if (!('invite' in value) || value['invite'] === undefined) return false;
    return true;
}

export function CreateInviteResponseFromJSON(json: any): CreateInviteResponse {
    return CreateInviteResponseFromJSONTyped(json, false);
}

export function CreateInviteResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateInviteResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'invite_token': json['invite_token'],
        'invite': InviteFromJSON(json['invite']),
    };
}

export function CreateInviteResponseToJSON(json: any): CreateInviteResponse {
    return CreateInviteResponseToJSONTyped(json, false);
}

export function CreateInviteResponseToJSONTyped(value?: CreateInviteResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'invite_token': value['invite_token'],
        'invite': InviteToJSON(value['invite']),
    };
}

