/* tslint:disable */
/* eslint-disable */
/**
 * DrawBridge API
 * DrawBridge backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
    UserToJSONTyped,
} from './User';

/**
 * 
 * @export
 * @interface CursorPageUser
 */
export interface CursorPageUser {
    /**
     * 
     * @type {Array<User>}
     * @memberof CursorPageUser
     */
    items: Array<User>;
    /**
     * 
     * @type {string}
     * @memberof CursorPageUser
     */
    next_cursor?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof CursorPageUser
     */
    has_more: boolean;
}

/**
 * Check if a given object implements the CursorPageUser interface.
 */
export function instanceOfCursorPageUser(value: object): value is CursorPageUser {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('has_more' in value) || value['has_more'] === undefined) return false;
    return true;
}

export function CursorPageUserFromJSON(json: any): CursorPageUser {
    return CursorPageUserFromJSONTyped(json, false);
}

export function CursorPageUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): CursorPageUser {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(UserFromJSON)),
        'next_cursor': json['next_cursor'] == null ? undefined : json['next_cursor'],
        'has_more': json['has_more'],
    };
}

export function CursorPageUserToJSON(json: any): CursorPageUser {
    return CursorPageUserToJSONTyped(json, false);
}

export function CursorPageUserToJSONTyped(value?: CursorPageUser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(UserToJSON)),
        'next_cursor': value['next_cursor'],
        'has_more': value['has_more'],
    };
}

