/* tslint:disable */
/* eslint-disable */
/**
 * DrawBridge API
 * DrawBridge backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TrainingRequest } from './TrainingRequest';
import {
    TrainingRequestFromJSON,
    TrainingRequestFromJSONTyped,
    TrainingRequestToJSON,
    TrainingRequestToJSONTyped,
} from './TrainingRequest';

/**
 * 
 * @export
 * @interface CursorPageTrainingRequest
 */
export interface CursorPageTrainingRequest {
    /**
     * 
     * @type {Array<TrainingRequest>}
     * @memberof CursorPageTrainingRequest
     */
    items: Array<TrainingRequest>;
    /**
     * 
     * @type {string}
     * @memberof CursorPageTrainingRequest
     */
    next_cursor?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof CursorPageTrainingRequest
     */
    has_more: boolean;
}

/**
 * Check if a given object implements the CursorPageTrainingRequest interface.
 */
export function instanceOfCursorPageTrainingRequest(value: object): value is CursorPageTrainingRequest {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('has_more' in value) || value['has_more'] === undefined) return false;
    return true;
}

export function CursorPageTrainingRequestFromJSON(json: any): CursorPageTrainingRequest {
    return CursorPageTrainingRequestFromJSONTyped(json, false);
}

export function CursorPageTrainingRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CursorPageTrainingRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(TrainingRequestFromJSON)),
        'next_cursor': json['next_cursor'] == null ? undefined : json['next_cursor'],
        'has_more': json['has_more'],
    };
}

export function CursorPageTrainingRequestToJSON(json: any): CursorPageTrainingRequest {
    return CursorPageTrainingRequestToJSONTyped(json, false);
}

export function CursorPageTrainingRequestToJSONTyped(value?: CursorPageTrainingRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(TrainingRequestToJSON)),
        'next_cursor': value['next_cursor'],
        'has_more': value['has_more'],
    };
}

