/* tslint:disable */
/* eslint-disable */
/**
 * DrawBridge API
 * DrawBridge backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Organization } from './Organization';
import {
    OrganizationFromJSON,
    OrganizationFromJSONTyped,
    OrganizationToJSON,
    OrganizationToJSONTyped,
} from './Organization';

/**
 * 
 * @export
 * @interface CursorPageOrganization
 */
export interface CursorPageOrganization {
    /**
     * 
     * @type {Array<Organization>}
     * @memberof CursorPageOrganization
     */
    items: Array<Organization>;
    /**
     * 
     * @type {string}
     * @memberof CursorPageOrganization
     */
    next_cursor?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof CursorPageOrganization
     */
    has_more: boolean;
}

/**
 * Check if a given object implements the CursorPageOrganization interface.
 */
export function instanceOfCursorPageOrganization(value: object): value is CursorPageOrganization {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('has_more' in value) || value['has_more'] === undefined) return false;
    return true;
}

export function CursorPageOrganizationFromJSON(json: any): CursorPageOrganization {
    return CursorPageOrganizationFromJSONTyped(json, false);
}

export function CursorPageOrganizationFromJSONTyped(json: any, ignoreDiscriminator: boolean): CursorPageOrganization {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(OrganizationFromJSON)),
        'next_cursor': json['next_cursor'] == null ? undefined : json['next_cursor'],
        'has_more': json['has_more'],
    };
}

export function CursorPageOrganizationToJSON(json: any): CursorPageOrganization {
    return CursorPageOrganizationToJSONTyped(json, false);
}

export function CursorPageOrganizationToJSONTyped(value?: CursorPageOrganization | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(OrganizationToJSON)),
        'next_cursor': value['next_cursor'],
        'has_more': value['has_more'],
    };
}

