/* tslint:disable */
/* eslint-disable */
/**
 * DrawBridge API
 * DrawBridge backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AuditEvent } from './AuditEvent';
import {
    AuditEventFromJSON,
    AuditEventFromJSONTyped,
    AuditEventToJSON,
    AuditEventToJSONTyped,
} from './AuditEvent';

/**
 * 
 * @export
 * @interface CursorPageAuditEvent
 */
export interface CursorPageAuditEvent {
    /**
     * 
     * @type {Array<AuditEvent>}
     * @memberof CursorPageAuditEvent
     */
    items: Array<AuditEvent>;
    /**
     * 
     * @type {string}
     * @memberof CursorPageAuditEvent
     */
    next_cursor?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof CursorPageAuditEvent
     */
    has_more: boolean;
}

/**
 * Check if a given object implements the CursorPageAuditEvent interface.
 */
export function instanceOfCursorPageAuditEvent(value: object): value is CursorPageAuditEvent {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('has_more' in value) || value['has_more'] === undefined) return false;
    return true;
}

export function CursorPageAuditEventFromJSON(json: any): CursorPageAuditEvent {
    return CursorPageAuditEventFromJSONTyped(json, false);
}

export function CursorPageAuditEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): CursorPageAuditEvent {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(AuditEventFromJSON)),
        'next_cursor': json['next_cursor'] == null ? undefined : json['next_cursor'],
        'has_more': json['has_more'],
    };
}

export function CursorPageAuditEventToJSON(json: any): CursorPageAuditEvent {
    return CursorPageAuditEventToJSONTyped(json, false);
}

export function CursorPageAuditEventToJSONTyped(value?: CursorPageAuditEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(AuditEventToJSON)),
        'next_cursor': value['next_cursor'],
        'has_more': value['has_more'],
    };
}

