/* tslint:disable */
/* eslint-disable */
/**
 * DrawBridge API
 * DrawBridge backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Product } from './Product';
import {
    ProductFromJSON,
    ProductFromJSONTyped,
    ProductToJSON,
    ProductToJSONTyped,
} from './Product';

/**
 * 
 * @export
 * @interface CursorPageProduct
 */
export interface CursorPageProduct {
    /**
     * 
     * @type {Array<Product>}
     * @memberof CursorPageProduct
     */
    items: Array<Product>;
    /**
     * 
     * @type {string}
     * @memberof CursorPageProduct
     */
    next_cursor?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof CursorPageProduct
     */
    has_more: boolean;
}

/**
 * Check if a given object implements the CursorPageProduct interface.
 */
export function instanceOfCursorPageProduct(value: object): value is CursorPageProduct {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('has_more' in value) || value['has_more'] === undefined) return false;
    return true;
}

export function CursorPageProductFromJSON(json: any): CursorPageProduct {
    return CursorPageProductFromJSONTyped(json, false);
}

export function CursorPageProductFromJSONTyped(json: any, ignoreDiscriminator: boolean): CursorPageProduct {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(ProductFromJSON)),
        'next_cursor': json['next_cursor'] == null ? undefined : json['next_cursor'],
        'has_more': json['has_more'],
    };
}

export function CursorPageProductToJSON(json: any): CursorPageProduct {
    return CursorPageProductToJSONTyped(json, false);
}

export function CursorPageProductToJSONTyped(value?: CursorPageProduct | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(ProductToJSON)),
        'next_cursor': value['next_cursor'],
        'has_more': value['has_more'],
    };
}

