/* tslint:disable */
/* eslint-disable */
/**
 * MedBridge API
 * MedBridge backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ErrorResponseError
 */
export interface ErrorResponseError {
    /**
     * 
     * @type {string}
     * @memberof ErrorResponseError
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof ErrorResponseError
     */
    message: string;
}

/**
 * Check if a given object implements the ErrorResponseError interface.
 */
export function instanceOfErrorResponseError(value: object): value is ErrorResponseError {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function ErrorResponseErrorFromJSON(json: any): ErrorResponseError {
    return ErrorResponseErrorFromJSONTyped(json, false);
}

export function ErrorResponseErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorResponseError {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'message': json['message'],
    };
}

export function ErrorResponseErrorToJSON(json: any): ErrorResponseError {
    return ErrorResponseErrorToJSONTyped(json, false);
}

export function ErrorResponseErrorToJSONTyped(value?: ErrorResponseError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
    };
}

