/* tslint:disable */
/* eslint-disable */
/**
 * DrawBridge API
 * DrawBridge backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WebinarParticipantRole } from './WebinarParticipantRole';
import {
    WebinarParticipantRoleFromJSON,
    WebinarParticipantRoleFromJSONTyped,
    WebinarParticipantRoleToJSON,
    WebinarParticipantRoleToJSONTyped,
} from './WebinarParticipantRole';

/**
 * 
 * @export
 * @interface JoinWebinarRequest
 */
export interface JoinWebinarRequest {
    /**
     * Deprecated and ignored by the backend; participant role is derived from caller permissions.
     * @type {WebinarParticipantRole}
     * @memberof JoinWebinarRequest
     * @deprecated
     */
    participant_role?: WebinarParticipantRole;
}



/**
 * Check if a given object implements the JoinWebinarRequest interface.
 */
export function instanceOfJoinWebinarRequest(value: object): value is JoinWebinarRequest {
    return true;
}

export function JoinWebinarRequestFromJSON(json: any): JoinWebinarRequest {
    return JoinWebinarRequestFromJSONTyped(json, false);
}

export function JoinWebinarRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoinWebinarRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'participant_role': json['participant_role'] == null ? undefined : WebinarParticipantRoleFromJSON(json['participant_role']),
    };
}

export function JoinWebinarRequestToJSON(json: any): JoinWebinarRequest {
    return JoinWebinarRequestToJSONTyped(json, false);
}

export function JoinWebinarRequestToJSONTyped(value?: JoinWebinarRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'participant_role': WebinarParticipantRoleToJSON(value['participant_role']),
    };
}

