/* tslint:disable */
/* eslint-disable */
/**
 * MedBridge API
 * MedBridge backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Organization } from './Organization';
import {
    OrganizationFromJSON,
    OrganizationFromJSONTyped,
    OrganizationToJSON,
    OrganizationToJSONTyped,
} from './Organization';

/**
 * 
 * @export
 * @interface ListOrganizationsResponse
 */
export interface ListOrganizationsResponse {
    /**
     * 
     * @type {Array<Organization>}
     * @memberof ListOrganizationsResponse
     */
    items: Array<Organization>;
    /**
     * 
     * @type {number}
     * @memberof ListOrganizationsResponse
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof ListOrganizationsResponse
     */
    page_size: number;
    /**
     * 
     * @type {number}
     * @memberof ListOrganizationsResponse
     */
    total: number;
}

/**
 * Check if a given object implements the ListOrganizationsResponse interface.
 */
export function instanceOfListOrganizationsResponse(value: object): value is ListOrganizationsResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('page_size' in value) || value['page_size'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function ListOrganizationsResponseFromJSON(json: any): ListOrganizationsResponse {
    return ListOrganizationsResponseFromJSONTyped(json, false);
}

export function ListOrganizationsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListOrganizationsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(OrganizationFromJSON)),
        'page': json['page'],
        'page_size': json['page_size'],
        'total': json['total'],
    };
}

export function ListOrganizationsResponseToJSON(json: any): ListOrganizationsResponse {
    return ListOrganizationsResponseToJSONTyped(json, false);
}

export function ListOrganizationsResponseToJSONTyped(value?: ListOrganizationsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(OrganizationToJSON)),
        'page': value['page'],
        'page_size': value['page_size'],
        'total': value['total'],
    };
}

