/* tslint:disable */
/* eslint-disable */
/**
 * MedBridge API
 * MedBridge backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Membership } from './Membership';
import {
    MembershipFromJSON,
    MembershipFromJSONTyped,
    MembershipToJSON,
    MembershipToJSONTyped,
} from './Membership';

/**
 * 
 * @export
 * @interface ListMembershipsResponse
 */
export interface ListMembershipsResponse {
    /**
     * 
     * @type {Array<Membership>}
     * @memberof ListMembershipsResponse
     */
    items: Array<Membership>;
}

/**
 * Check if a given object implements the ListMembershipsResponse interface.
 */
export function instanceOfListMembershipsResponse(value: object): value is ListMembershipsResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function ListMembershipsResponseFromJSON(json: any): ListMembershipsResponse {
    return ListMembershipsResponseFromJSONTyped(json, false);
}

export function ListMembershipsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListMembershipsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(MembershipFromJSON)),
    };
}

export function ListMembershipsResponseToJSON(json: any): ListMembershipsResponse {
    return ListMembershipsResponseToJSONTyped(json, false);
}

export function ListMembershipsResponseToJSONTyped(value?: ListMembershipsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(MembershipToJSON)),
    };
}

