/* tslint:disable */
/* eslint-disable */
/**
 * MedBridge API
 * MedBridge backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TrainingRequest } from './TrainingRequest';
import {
    TrainingRequestFromJSON,
    TrainingRequestFromJSONTyped,
    TrainingRequestToJSON,
    TrainingRequestToJSONTyped,
} from './TrainingRequest';

/**
 * 
 * @export
 * @interface ListTrainingRequestsResponse
 */
export interface ListTrainingRequestsResponse {
    /**
     * 
     * @type {Array<TrainingRequest>}
     * @memberof ListTrainingRequestsResponse
     */
    items: Array<TrainingRequest>;
    /**
     * 
     * @type {number}
     * @memberof ListTrainingRequestsResponse
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof ListTrainingRequestsResponse
     */
    page_size: number;
    /**
     * 
     * @type {number}
     * @memberof ListTrainingRequestsResponse
     */
    total: number;
}

/**
 * Check if a given object implements the ListTrainingRequestsResponse interface.
 */
export function instanceOfListTrainingRequestsResponse(value: object): value is ListTrainingRequestsResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('page_size' in value) || value['page_size'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function ListTrainingRequestsResponseFromJSON(json: any): ListTrainingRequestsResponse {
    return ListTrainingRequestsResponseFromJSONTyped(json, false);
}

export function ListTrainingRequestsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListTrainingRequestsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(TrainingRequestFromJSON)),
        'page': json['page'],
        'page_size': json['page_size'],
        'total': json['total'],
    };
}

export function ListTrainingRequestsResponseToJSON(json: any): ListTrainingRequestsResponse {
    return ListTrainingRequestsResponseToJSONTyped(json, false);
}

export function ListTrainingRequestsResponseToJSONTyped(value?: ListTrainingRequestsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(TrainingRequestToJSON)),
        'page': value['page'],
        'page_size': value['page_size'],
        'total': value['total'],
    };
}

