/* tslint:disable */
/* eslint-disable */
/**
 * MedBridge API
 * MedBridge backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RepCoverage } from './RepCoverage';
import {
    RepCoverageFromJSON,
    RepCoverageFromJSONTyped,
    RepCoverageToJSON,
    RepCoverageToJSONTyped,
} from './RepCoverage';

/**
 * 
 * @export
 * @interface ListRepCoveragesResponse
 */
export interface ListRepCoveragesResponse {
    /**
     * 
     * @type {Array<RepCoverage>}
     * @memberof ListRepCoveragesResponse
     */
    items: Array<RepCoverage>;
}

/**
 * Check if a given object implements the ListRepCoveragesResponse interface.
 */
export function instanceOfListRepCoveragesResponse(value: object): value is ListRepCoveragesResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function ListRepCoveragesResponseFromJSON(json: any): ListRepCoveragesResponse {
    return ListRepCoveragesResponseFromJSONTyped(json, false);
}

export function ListRepCoveragesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListRepCoveragesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(RepCoverageFromJSON)),
    };
}

export function ListRepCoveragesResponseToJSON(json: any): ListRepCoveragesResponse {
    return ListRepCoveragesResponseToJSONTyped(json, false);
}

export function ListRepCoveragesResponseToJSONTyped(value?: ListRepCoveragesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(RepCoverageToJSON)),
    };
}

