/* tslint:disable */
/* eslint-disable */
/**
 * MedBridge API
 * MedBridge backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MembershipStatus } from './MembershipStatus';
import {
    MembershipStatusFromJSON,
    MembershipStatusFromJSONTyped,
    MembershipStatusToJSON,
    MembershipStatusToJSONTyped,
} from './MembershipStatus';
import type { MembershipRole } from './MembershipRole';
import {
    MembershipRoleFromJSON,
    MembershipRoleFromJSONTyped,
    MembershipRoleToJSON,
    MembershipRoleToJSONTyped,
} from './MembershipRole';

/**
 * 
 * @export
 * @interface Membership
 */
export interface Membership {
    /**
     * 
     * @type {string}
     * @memberof Membership
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Membership
     */
    user_id: string;
    /**
     * 
     * @type {string}
     * @memberof Membership
     */
    organization_id: string;
    /**
     * 
     * @type {MembershipRole}
     * @memberof Membership
     */
    role: MembershipRole;
    /**
     * 
     * @type {MembershipStatus}
     * @memberof Membership
     */
    membership_status: MembershipStatus;
    /**
     * 
     * @type {Date}
     * @memberof Membership
     */
    created_at: Date;
    /**
     * 
     * @type {Date}
     * @memberof Membership
     */
    updated_at?: Date | null;
}



/**
 * Check if a given object implements the Membership interface.
 */
export function instanceOfMembership(value: object): value is Membership {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('user_id' in value) || value['user_id'] === undefined) return false;
    if (!('organization_id' in value) || value['organization_id'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    if (!('membership_status' in value) || value['membership_status'] === undefined) return false;
    if (!('created_at' in value) || value['created_at'] === undefined) return false;
    return true;
}

export function MembershipFromJSON(json: any): Membership {
    return MembershipFromJSONTyped(json, false);
}

export function MembershipFromJSONTyped(json: any, ignoreDiscriminator: boolean): Membership {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'user_id': json['user_id'],
        'organization_id': json['organization_id'],
        'role': MembershipRoleFromJSON(json['role']),
        'membership_status': MembershipStatusFromJSON(json['membership_status']),
        'created_at': (new Date(json['created_at'])),
        'updated_at': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
    };
}

export function MembershipToJSON(json: any): Membership {
    return MembershipToJSONTyped(json, false);
}

export function MembershipToJSONTyped(value?: Membership | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'user_id': value['user_id'],
        'organization_id': value['organization_id'],
        'role': MembershipRoleToJSON(value['role']),
        'membership_status': MembershipStatusToJSON(value['membership_status']),
        'created_at': value['created_at'].toISOString(),
        'updated_at': value['updated_at'] == null ? value['updated_at'] : value['updated_at'].toISOString(),
    };
}

