/* tslint:disable */
/* eslint-disable */
/**
 * MedBridge API
 * MedBridge backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const MembershipRole = {
    HospitalUser: 'hospital_user',
    Rep: 'rep',
    VendorAdmin: 'vendor_admin',
    OrgAdmin: 'org_admin'
} as const;
export type MembershipRole = typeof MembershipRole[keyof typeof MembershipRole];


export function instanceOfMembershipRole(value: any): boolean {
    for (const key in MembershipRole) {
        if (Object.prototype.hasOwnProperty.call(MembershipRole, key)) {
            if (MembershipRole[key as keyof typeof MembershipRole] === value) {
                return true;
            }
        }
    }
    return false;
}

export function MembershipRoleFromJSON(json: any): MembershipRole {
    return MembershipRoleFromJSONTyped(json, false);
}

export function MembershipRoleFromJSONTyped(json: any, ignoreDiscriminator: boolean): MembershipRole {
    return json as MembershipRole;
}

export function MembershipRoleToJSON(value?: MembershipRole | null): any {
    return value as any;
}

export function MembershipRoleToJSONTyped(value: any, ignoreDiscriminator: boolean): MembershipRole {
    return value as MembershipRole;
}

