/* tslint:disable */
/* eslint-disable */
/**
 * MedBridge API
 * MedBridge backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const OnboardingState = {
    Prospect: 'prospect',
    Invited: 'invited',
    InProgress: 'in_progress',
    Active: 'active',
    Inactive: 'inactive'
} as const;
export type OnboardingState = typeof OnboardingState[keyof typeof OnboardingState];


export function instanceOfOnboardingState(value: any): boolean {
    for (const key in OnboardingState) {
        if (Object.prototype.hasOwnProperty.call(OnboardingState, key)) {
            if (OnboardingState[key as keyof typeof OnboardingState] === value) {
                return true;
            }
        }
    }
    return false;
}

export function OnboardingStateFromJSON(json: any): OnboardingState {
    return OnboardingStateFromJSONTyped(json, false);
}

export function OnboardingStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): OnboardingState {
    return json as OnboardingState;
}

export function OnboardingStateToJSON(value?: OnboardingState | null): any {
    return value as any;
}

export function OnboardingStateToJSONTyped(value: any, ignoreDiscriminator: boolean): OnboardingState {
    return value as OnboardingState;
}

