/* tslint:disable */
/* eslint-disable */
/**
 * MedBridge API
 * MedBridge backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OnboardingState } from './OnboardingState';
import {
    OnboardingStateFromJSON,
    OnboardingStateFromJSONTyped,
    OnboardingStateToJSON,
    OnboardingStateToJSONTyped,
} from './OnboardingState';
import type { OrganizationType } from './OrganizationType';
import {
    OrganizationTypeFromJSON,
    OrganizationTypeFromJSONTyped,
    OrganizationTypeToJSON,
    OrganizationTypeToJSONTyped,
} from './OrganizationType';

/**
 * 
 * @export
 * @interface Organization
 */
export interface Organization {
    /**
     * 
     * @type {string}
     * @memberof Organization
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Organization
     */
    name: string;
    /**
     * 
     * @type {Date}
     * @memberof Organization
     */
    date_added: Date;
    /**
     * 
     * @type {Date}
     * @memberof Organization
     */
    date_updated?: Date | null;
    /**
     * 
     * @type {OrganizationType}
     * @memberof Organization
     */
    org_type: OrganizationType;
    /**
     * 
     * @type {OnboardingState}
     * @memberof Organization
     */
    onboarding_status: OnboardingState;
    /**
     * 
     * @type {Date}
     * @memberof Organization
     */
    onboarded_at?: Date | null;
}



/**
 * Check if a given object implements the Organization interface.
 */
export function instanceOfOrganization(value: object): value is Organization {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('date_added' in value) || value['date_added'] === undefined) return false;
    if (!('org_type' in value) || value['org_type'] === undefined) return false;
    if (!('onboarding_status' in value) || value['onboarding_status'] === undefined) return false;
    return true;
}

export function OrganizationFromJSON(json: any): Organization {
    return OrganizationFromJSONTyped(json, false);
}

export function OrganizationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Organization {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'date_added': (new Date(json['date_added'])),
        'date_updated': json['date_updated'] == null ? undefined : (new Date(json['date_updated'])),
        'org_type': OrganizationTypeFromJSON(json['org_type']),
        'onboarding_status': OnboardingStateFromJSON(json['onboarding_status']),
        'onboarded_at': json['onboarded_at'] == null ? undefined : (new Date(json['onboarded_at'])),
    };
}

export function OrganizationToJSON(json: any): Organization {
    return OrganizationToJSONTyped(json, false);
}

export function OrganizationToJSONTyped(value?: Organization | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'date_added': value['date_added'].toISOString(),
        'date_updated': value['date_updated'] == null ? value['date_updated'] : value['date_updated'].toISOString(),
        'org_type': OrganizationTypeToJSON(value['org_type']),
        'onboarding_status': OnboardingStateToJSON(value['onboarding_status']),
        'onboarded_at': value['onboarded_at'] == null ? value['onboarded_at'] : value['onboarded_at'].toISOString(),
    };
}

