/* tslint:disable */
/* eslint-disable */
/**
 * DrawBridge API
 * DrawBridge backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrganizationRep
 */
export interface OrganizationRep {
    /**
     * 
     * @type {string}
     * @memberof OrganizationRep
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationRep
     */
    organization_id: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationRep
     */
    user_id: string;
    /**
     * 
     * @type {Date}
     * @memberof OrganizationRep
     */
    date_added: Date;
    /**
     * 
     * @type {Date}
     * @memberof OrganizationRep
     */
    date_updated?: Date | null;
}

/**
 * Check if a given object implements the OrganizationRep interface.
 */
export function instanceOfOrganizationRep(value: object): value is OrganizationRep {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('organization_id' in value) || value['organization_id'] === undefined) return false;
    if (!('user_id' in value) || value['user_id'] === undefined) return false;
    if (!('date_added' in value) || value['date_added'] === undefined) return false;
    return true;
}

export function OrganizationRepFromJSON(json: any): OrganizationRep {
    return OrganizationRepFromJSONTyped(json, false);
}

export function OrganizationRepFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationRep {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'organization_id': json['organization_id'],
        'user_id': json['user_id'],
        'date_added': (new Date(json['date_added'])),
        'date_updated': json['date_updated'] == null ? undefined : (new Date(json['date_updated'])),
    };
}

export function OrganizationRepToJSON(json: any): OrganizationRep {
    return OrganizationRepToJSONTyped(json, false);
}

export function OrganizationRepToJSONTyped(value?: OrganizationRep | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'organization_id': value['organization_id'],
        'user_id': value['user_id'],
        'date_added': value['date_added'].toISOString(),
        'date_updated': value['date_updated'] == null ? value['date_updated'] : value['date_updated'].toISOString(),
    };
}

