/* tslint:disable */
/* eslint-disable */
/**
 * MedBridge API
 * MedBridge backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrganizationRelationType } from './OrganizationRelationType';
import {
    OrganizationRelationTypeFromJSON,
    OrganizationRelationTypeFromJSONTyped,
    OrganizationRelationTypeToJSON,
    OrganizationRelationTypeToJSONTyped,
} from './OrganizationRelationType';

/**
 * 
 * @export
 * @interface OrganizationRelation
 */
export interface OrganizationRelation {
    /**
     * 
     * @type {string}
     * @memberof OrganizationRelation
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationRelation
     */
    parent_organization_id: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationRelation
     */
    child_organization_id: string;
    /**
     * 
     * @type {Date}
     * @memberof OrganizationRelation
     */
    date_added: Date;
    /**
     * 
     * @type {OrganizationRelationType}
     * @memberof OrganizationRelation
     */
    relation_type: OrganizationRelationType;
}



/**
 * Check if a given object implements the OrganizationRelation interface.
 */
export function instanceOfOrganizationRelation(value: object): value is OrganizationRelation {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('parent_organization_id' in value) || value['parent_organization_id'] === undefined) return false;
    if (!('child_organization_id' in value) || value['child_organization_id'] === undefined) return false;
    if (!('date_added' in value) || value['date_added'] === undefined) return false;
    if (!('relation_type' in value) || value['relation_type'] === undefined) return false;
    return true;
}

export function OrganizationRelationFromJSON(json: any): OrganizationRelation {
    return OrganizationRelationFromJSONTyped(json, false);
}

export function OrganizationRelationFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationRelation {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'parent_organization_id': json['parent_organization_id'],
        'child_organization_id': json['child_organization_id'],
        'date_added': (new Date(json['date_added'])),
        'relation_type': OrganizationRelationTypeFromJSON(json['relation_type']),
    };
}

export function OrganizationRelationToJSON(json: any): OrganizationRelation {
    return OrganizationRelationToJSONTyped(json, false);
}

export function OrganizationRelationToJSONTyped(value?: OrganizationRelation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'parent_organization_id': value['parent_organization_id'],
        'child_organization_id': value['child_organization_id'],
        'date_added': value['date_added'].toISOString(),
        'relation_type': OrganizationRelationTypeToJSON(value['relation_type']),
    };
}

