/* tslint:disable */
/* eslint-disable */
/**
 * MedBridge API
 * MedBridge backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchProductRequest
 */
export interface PatchProductRequest {
    /**
     * 
     * @type {string}
     * @memberof PatchProductRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchProductRequest
     */
    description?: string | null;
}

/**
 * Check if a given object implements the PatchProductRequest interface.
 */
export function instanceOfPatchProductRequest(value: object): value is PatchProductRequest {
    return true;
}

export function PatchProductRequestFromJSON(json: any): PatchProductRequest {
    return PatchProductRequestFromJSONTyped(json, false);
}

export function PatchProductRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchProductRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function PatchProductRequestToJSON(json: any): PatchProductRequest {
    return PatchProductRequestToJSONTyped(json, false);
}

export function PatchProductRequestToJSONTyped(value?: PatchProductRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
    };
}

