/* tslint:disable */
/* eslint-disable */
/**
 * MedBridge API
 * MedBridge backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OnboardingState } from './OnboardingState';
import {
    OnboardingStateFromJSON,
    OnboardingStateFromJSONTyped,
    OnboardingStateToJSON,
    OnboardingStateToJSONTyped,
} from './OnboardingState';

/**
 * 
 * @export
 * @interface PatchOrganizationRequest
 */
export interface PatchOrganizationRequest {
    /**
     * 
     * @type {string}
     * @memberof PatchOrganizationRequest
     */
    name?: string;
    /**
     * 
     * @type {OnboardingState}
     * @memberof PatchOrganizationRequest
     */
    onboarding_status?: OnboardingState;
}



/**
 * Check if a given object implements the PatchOrganizationRequest interface.
 */
export function instanceOfPatchOrganizationRequest(value: object): value is PatchOrganizationRequest {
    return true;
}

export function PatchOrganizationRequestFromJSON(json: any): PatchOrganizationRequest {
    return PatchOrganizationRequestFromJSONTyped(json, false);
}

export function PatchOrganizationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchOrganizationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'onboarding_status': json['onboarding_status'] == null ? undefined : OnboardingStateFromJSON(json['onboarding_status']),
    };
}

export function PatchOrganizationRequestToJSON(json: any): PatchOrganizationRequest {
    return PatchOrganizationRequestToJSONTyped(json, false);
}

export function PatchOrganizationRequestToJSONTyped(value?: PatchOrganizationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'onboarding_status': OnboardingStateToJSON(value['onboarding_status']),
    };
}

