/* tslint:disable */
/* eslint-disable */
/**
 * MedBridge API
 * MedBridge backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProductOrganization
 */
export interface ProductOrganization {
    /**
     * 
     * @type {string}
     * @memberof ProductOrganization
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ProductOrganization
     */
    product_id: string;
    /**
     * 
     * @type {string}
     * @memberof ProductOrganization
     */
    organization_id: string;
    /**
     * 
     * @type {Date}
     * @memberof ProductOrganization
     */
    date_added: Date;
}

/**
 * Check if a given object implements the ProductOrganization interface.
 */
export function instanceOfProductOrganization(value: object): value is ProductOrganization {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('product_id' in value) || value['product_id'] === undefined) return false;
    if (!('organization_id' in value) || value['organization_id'] === undefined) return false;
    if (!('date_added' in value) || value['date_added'] === undefined) return false;
    return true;
}

export function ProductOrganizationFromJSON(json: any): ProductOrganization {
    return ProductOrganizationFromJSONTyped(json, false);
}

export function ProductOrganizationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductOrganization {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'product_id': json['product_id'],
        'organization_id': json['organization_id'],
        'date_added': (new Date(json['date_added'])),
    };
}

export function ProductOrganizationToJSON(json: any): ProductOrganization {
    return ProductOrganizationToJSONTyped(json, false);
}

export function ProductOrganizationToJSONTyped(value?: ProductOrganization | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'product_id': value['product_id'],
        'organization_id': value['organization_id'],
        'date_added': value['date_added'].toISOString(),
    };
}

