/* tslint:disable */
/* eslint-disable */
/**
 * DrawBridge API
 * DrawBridge backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RepAvailabilityStatus } from './RepAvailabilityStatus';
import {
    RepAvailabilityStatusFromJSON,
    RepAvailabilityStatusFromJSONTyped,
    RepAvailabilityStatusToJSON,
    RepAvailabilityStatusToJSONTyped,
} from './RepAvailabilityStatus';
import type { RepAvailabilityWindowType } from './RepAvailabilityWindowType';
import {
    RepAvailabilityWindowTypeFromJSON,
    RepAvailabilityWindowTypeFromJSONTyped,
    RepAvailabilityWindowTypeToJSON,
    RepAvailabilityWindowTypeToJSONTyped,
} from './RepAvailabilityWindowType';

/**
 * 
 * @export
 * @interface RepAvailabilityWindow
 */
export interface RepAvailabilityWindow {
    /**
     * 
     * @type {string}
     * @memberof RepAvailabilityWindow
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof RepAvailabilityWindow
     */
    rep_user_id: string;
    /**
     * 
     * @type {RepAvailabilityWindowType}
     * @memberof RepAvailabilityWindow
     */
    window_type: RepAvailabilityWindowType;
    /**
     * 
     * @type {Date}
     * @memberof RepAvailabilityWindow
     */
    starts_at?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof RepAvailabilityWindow
     */
    ends_at?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof RepAvailabilityWindow
     */
    weekday?: number | null;
    /**
     * 
     * @type {number}
     * @memberof RepAvailabilityWindow
     */
    start_minute?: number | null;
    /**
     * 
     * @type {number}
     * @memberof RepAvailabilityWindow
     */
    end_minute?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof RepAvailabilityWindow
     */
    effective_from?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof RepAvailabilityWindow
     */
    effective_until?: Date | null;
    /**
     * 
     * @type {RepAvailabilityStatus}
     * @memberof RepAvailabilityWindow
     */
    status: RepAvailabilityStatus;
    /**
     * 
     * @type {string}
     * @memberof RepAvailabilityWindow
     */
    note?: string;
    /**
     * 
     * @type {Date}
     * @memberof RepAvailabilityWindow
     */
    date_added: Date;
    /**
     * 
     * @type {Date}
     * @memberof RepAvailabilityWindow
     */
    date_updated?: Date | null;
}



/**
 * Check if a given object implements the RepAvailabilityWindow interface.
 */
export function instanceOfRepAvailabilityWindow(value: object): value is RepAvailabilityWindow {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('rep_user_id' in value) || value['rep_user_id'] === undefined) return false;
    if (!('window_type' in value) || value['window_type'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('date_added' in value) || value['date_added'] === undefined) return false;
    return true;
}

export function RepAvailabilityWindowFromJSON(json: any): RepAvailabilityWindow {
    return RepAvailabilityWindowFromJSONTyped(json, false);
}

export function RepAvailabilityWindowFromJSONTyped(json: any, ignoreDiscriminator: boolean): RepAvailabilityWindow {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'rep_user_id': json['rep_user_id'],
        'window_type': RepAvailabilityWindowTypeFromJSON(json['window_type']),
        'starts_at': json['starts_at'] == null ? undefined : (new Date(json['starts_at'])),
        'ends_at': json['ends_at'] == null ? undefined : (new Date(json['ends_at'])),
        'weekday': json['weekday'] == null ? undefined : json['weekday'],
        'start_minute': json['start_minute'] == null ? undefined : json['start_minute'],
        'end_minute': json['end_minute'] == null ? undefined : json['end_minute'],
        'effective_from': json['effective_from'] == null ? undefined : (new Date(json['effective_from'])),
        'effective_until': json['effective_until'] == null ? undefined : (new Date(json['effective_until'])),
        'status': RepAvailabilityStatusFromJSON(json['status']),
        'note': json['note'] == null ? undefined : json['note'],
        'date_added': (new Date(json['date_added'])),
        'date_updated': json['date_updated'] == null ? undefined : (new Date(json['date_updated'])),
    };
}

export function RepAvailabilityWindowToJSON(json: any): RepAvailabilityWindow {
    return RepAvailabilityWindowToJSONTyped(json, false);
}

export function RepAvailabilityWindowToJSONTyped(value?: RepAvailabilityWindow | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'rep_user_id': value['rep_user_id'],
        'window_type': RepAvailabilityWindowTypeToJSON(value['window_type']),
        'starts_at': value['starts_at'] == null ? value['starts_at'] : value['starts_at'].toISOString(),
        'ends_at': value['ends_at'] == null ? value['ends_at'] : value['ends_at'].toISOString(),
        'weekday': value['weekday'],
        'start_minute': value['start_minute'],
        'end_minute': value['end_minute'],
        'effective_from': value['effective_from'] == null ? value['effective_from'] : value['effective_from'].toISOString().substring(0,10),
        'effective_until': value['effective_until'] == null ? value['effective_until'] : value['effective_until'].toISOString().substring(0,10),
        'status': RepAvailabilityStatusToJSON(value['status']),
        'note': value['note'],
        'date_added': value['date_added'].toISOString(),
        'date_updated': value['date_updated'] == null ? value['date_updated'] : value['date_updated'].toISOString(),
    };
}

