/* tslint:disable */
/* eslint-disable */
/**
 * DrawBridge API
 * DrawBridge backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const RepAvailabilityStatus = {
    Available: 'available',
    Unavailable: 'unavailable',
    Remote: 'remote'
} as const;
export type RepAvailabilityStatus = typeof RepAvailabilityStatus[keyof typeof RepAvailabilityStatus];


export function instanceOfRepAvailabilityStatus(value: any): boolean {
    for (const key in RepAvailabilityStatus) {
        if (Object.prototype.hasOwnProperty.call(RepAvailabilityStatus, key)) {
            if (RepAvailabilityStatus[key as keyof typeof RepAvailabilityStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function RepAvailabilityStatusFromJSON(json: any): RepAvailabilityStatus {
    return RepAvailabilityStatusFromJSONTyped(json, false);
}

export function RepAvailabilityStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): RepAvailabilityStatus {
    return json as RepAvailabilityStatus;
}

export function RepAvailabilityStatusToJSON(value?: RepAvailabilityStatus | null): any {
    return value as any;
}

export function RepAvailabilityStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): RepAvailabilityStatus {
    return value as RepAvailabilityStatus;
}

