/* tslint:disable */
/* eslint-disable */
/**
 * DrawBridge API
 * DrawBridge backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const RepAvailabilityWindowType = {
    OneOff: 'one_off',
    Recurring: 'recurring'
} as const;
export type RepAvailabilityWindowType = typeof RepAvailabilityWindowType[keyof typeof RepAvailabilityWindowType];


export function instanceOfRepAvailabilityWindowType(value: any): boolean {
    for (const key in RepAvailabilityWindowType) {
        if (Object.prototype.hasOwnProperty.call(RepAvailabilityWindowType, key)) {
            if (RepAvailabilityWindowType[key as keyof typeof RepAvailabilityWindowType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function RepAvailabilityWindowTypeFromJSON(json: any): RepAvailabilityWindowType {
    return RepAvailabilityWindowTypeFromJSONTyped(json, false);
}

export function RepAvailabilityWindowTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): RepAvailabilityWindowType {
    return json as RepAvailabilityWindowType;
}

export function RepAvailabilityWindowTypeToJSON(value?: RepAvailabilityWindowType | null): any {
    return value as any;
}

export function RepAvailabilityWindowTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): RepAvailabilityWindowType {
    return value as RepAvailabilityWindowType;
}

