/* tslint:disable */
/* eslint-disable */
/**
 * DrawBridge API
 * DrawBridge backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RepAssignedAccount
 */
export interface RepAssignedAccount {
    /**
     * 
     * @type {string}
     * @memberof RepAssignedAccount
     */
    organization_id: string;
    /**
     * 
     * @type {string}
     * @memberof RepAssignedAccount
     */
    organization_name: string;
    /**
     * 
     * @type {string}
     * @memberof RepAssignedAccount
     */
    organization_type: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof RepAssignedAccount
     */
    product_ids: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof RepAssignedAccount
     */
    product_names: Array<string>;
}

/**
 * Check if a given object implements the RepAssignedAccount interface.
 */
export function instanceOfRepAssignedAccount(value: object): value is RepAssignedAccount {
    if (!('organization_id' in value) || value['organization_id'] === undefined) return false;
    if (!('organization_name' in value) || value['organization_name'] === undefined) return false;
    if (!('organization_type' in value) || value['organization_type'] === undefined) return false;
    if (!('product_ids' in value) || value['product_ids'] === undefined) return false;
    if (!('product_names' in value) || value['product_names'] === undefined) return false;
    return true;
}

export function RepAssignedAccountFromJSON(json: any): RepAssignedAccount {
    return RepAssignedAccountFromJSONTyped(json, false);
}

export function RepAssignedAccountFromJSONTyped(json: any, ignoreDiscriminator: boolean): RepAssignedAccount {
    if (json == null) {
        return json;
    }
    return {
        
        'organization_id': json['organization_id'],
        'organization_name': json['organization_name'],
        'organization_type': json['organization_type'],
        'product_ids': json['product_ids'],
        'product_names': json['product_names'],
    };
}

export function RepAssignedAccountToJSON(json: any): RepAssignedAccount {
    return RepAssignedAccountToJSONTyped(json, false);
}

export function RepAssignedAccountToJSONTyped(value?: RepAssignedAccount | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'organization_id': value['organization_id'],
        'organization_name': value['organization_name'],
        'organization_type': value['organization_type'],
        'product_ids': value['product_ids'],
        'product_names': value['product_names'],
    };
}

