/* tslint:disable */
/* eslint-disable */
/**
 * MedBridge API
 * MedBridge backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CoverageStatus } from './CoverageStatus';
import {
    CoverageStatusFromJSON,
    CoverageStatusFromJSONTyped,
    CoverageStatusToJSON,
    CoverageStatusToJSONTyped,
} from './CoverageStatus';

/**
 * 
 * @export
 * @interface RepCoverage
 */
export interface RepCoverage {
    /**
     * 
     * @type {string}
     * @memberof RepCoverage
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof RepCoverage
     */
    rep_user_id: string;
    /**
     * 
     * @type {string}
     * @memberof RepCoverage
     */
    hospital_organization_id: string;
    /**
     * 
     * @type {string}
     * @memberof RepCoverage
     */
    product_id?: string | null;
    /**
     * 
     * @type {CoverageStatus}
     * @memberof RepCoverage
     */
    status: CoverageStatus;
    /**
     * 
     * @type {Date}
     * @memberof RepCoverage
     */
    created_at: Date;
    /**
     * 
     * @type {Date}
     * @memberof RepCoverage
     */
    updated_at?: Date | null;
}



/**
 * Check if a given object implements the RepCoverage interface.
 */
export function instanceOfRepCoverage(value: object): value is RepCoverage {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('rep_user_id' in value) || value['rep_user_id'] === undefined) return false;
    if (!('hospital_organization_id' in value) || value['hospital_organization_id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('created_at' in value) || value['created_at'] === undefined) return false;
    return true;
}

export function RepCoverageFromJSON(json: any): RepCoverage {
    return RepCoverageFromJSONTyped(json, false);
}

export function RepCoverageFromJSONTyped(json: any, ignoreDiscriminator: boolean): RepCoverage {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'rep_user_id': json['rep_user_id'],
        'hospital_organization_id': json['hospital_organization_id'],
        'product_id': json['product_id'] == null ? undefined : json['product_id'],
        'status': CoverageStatusFromJSON(json['status']),
        'created_at': (new Date(json['created_at'])),
        'updated_at': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
    };
}

export function RepCoverageToJSON(json: any): RepCoverage {
    return RepCoverageToJSONTyped(json, false);
}

export function RepCoverageToJSONTyped(value?: RepCoverage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'rep_user_id': value['rep_user_id'],
        'hospital_organization_id': value['hospital_organization_id'],
        'product_id': value['product_id'],
        'status': CoverageStatusToJSON(value['status']),
        'created_at': value['created_at'].toISOString(),
        'updated_at': value['updated_at'] == null ? value['updated_at'] : value['updated_at'].toISOString(),
    };
}

