/* tslint:disable */
/* eslint-disable */
/**
 * DrawBridge API
 * DrawBridge backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RepDirectoryEntry
 */
export interface RepDirectoryEntry {
    /**
     * 
     * @type {string}
     * @memberof RepDirectoryEntry
     */
    user_id: string;
    /**
     * 
     * @type {string}
     * @memberof RepDirectoryEntry
     */
    first_name: string;
    /**
     * 
     * @type {string}
     * @memberof RepDirectoryEntry
     */
    last_name: string;
    /**
     * 
     * @type {string}
     * @memberof RepDirectoryEntry
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof RepDirectoryEntry
     */
    phone_number?: string;
    /**
     * 
     * @type {string}
     * @memberof RepDirectoryEntry
     */
    vendor_organization_id?: string;
    /**
     * 
     * @type {string}
     * @memberof RepDirectoryEntry
     */
    vendor_organization_name?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof RepDirectoryEntry
     */
    product_ids: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof RepDirectoryEntry
     */
    product_names: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof RepDirectoryEntry
     */
    account_organization_ids: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof RepDirectoryEntry
     */
    account_organization_names: Array<string>;
}

/**
 * Check if a given object implements the RepDirectoryEntry interface.
 */
export function instanceOfRepDirectoryEntry(value: object): value is RepDirectoryEntry {
    if (!('user_id' in value) || value['user_id'] === undefined) return false;
    if (!('first_name' in value) || value['first_name'] === undefined) return false;
    if (!('last_name' in value) || value['last_name'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('product_ids' in value) || value['product_ids'] === undefined) return false;
    if (!('product_names' in value) || value['product_names'] === undefined) return false;
    if (!('account_organization_ids' in value) || value['account_organization_ids'] === undefined) return false;
    if (!('account_organization_names' in value) || value['account_organization_names'] === undefined) return false;
    return true;
}

export function RepDirectoryEntryFromJSON(json: any): RepDirectoryEntry {
    return RepDirectoryEntryFromJSONTyped(json, false);
}

export function RepDirectoryEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): RepDirectoryEntry {
    if (json == null) {
        return json;
    }
    return {
        
        'user_id': json['user_id'],
        'first_name': json['first_name'],
        'last_name': json['last_name'],
        'email': json['email'],
        'phone_number': json['phone_number'] == null ? undefined : json['phone_number'],
        'vendor_organization_id': json['vendor_organization_id'] == null ? undefined : json['vendor_organization_id'],
        'vendor_organization_name': json['vendor_organization_name'] == null ? undefined : json['vendor_organization_name'],
        'product_ids': json['product_ids'],
        'product_names': json['product_names'],
        'account_organization_ids': json['account_organization_ids'],
        'account_organization_names': json['account_organization_names'],
    };
}

export function RepDirectoryEntryToJSON(json: any): RepDirectoryEntry {
    return RepDirectoryEntryToJSONTyped(json, false);
}

export function RepDirectoryEntryToJSONTyped(value?: RepDirectoryEntry | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user_id': value['user_id'],
        'first_name': value['first_name'],
        'last_name': value['last_name'],
        'email': value['email'],
        'phone_number': value['phone_number'],
        'vendor_organization_id': value['vendor_organization_id'],
        'vendor_organization_name': value['vendor_organization_name'],
        'product_ids': value['product_ids'],
        'product_names': value['product_names'],
        'account_organization_ids': value['account_organization_ids'],
        'account_organization_names': value['account_organization_names'],
    };
}

