/* tslint:disable */
/* eslint-disable */
/**
 * DrawBridge API
 * DrawBridge backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const TrainingRequestStatus = {
    Requested: 'requested',
    Acknowledged: 'acknowledged',
    Scheduled: 'scheduled',
    Completed: 'completed',
    Cancelled: 'cancelled'
} as const;
export type TrainingRequestStatus = typeof TrainingRequestStatus[keyof typeof TrainingRequestStatus];


export function instanceOfTrainingRequestStatus(value: any): boolean {
    for (const key in TrainingRequestStatus) {
        if (Object.prototype.hasOwnProperty.call(TrainingRequestStatus, key)) {
            if (TrainingRequestStatus[key as keyof typeof TrainingRequestStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function TrainingRequestStatusFromJSON(json: any): TrainingRequestStatus {
    return TrainingRequestStatusFromJSONTyped(json, false);
}

export function TrainingRequestStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrainingRequestStatus {
    return json as TrainingRequestStatus;
}

export function TrainingRequestStatusToJSON(value?: TrainingRequestStatus | null): any {
    return value as any;
}

export function TrainingRequestStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): TrainingRequestStatus {
    return value as TrainingRequestStatus;
}

