/* tslint:disable */
/* eslint-disable */
/**
 * DrawBridge API
 * DrawBridge backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TrainingRequestStatus } from './TrainingRequestStatus';
import {
    TrainingRequestStatusFromJSON,
    TrainingRequestStatusFromJSONTyped,
    TrainingRequestStatusToJSON,
    TrainingRequestStatusToJSONTyped,
} from './TrainingRequestStatus';

/**
 * 
 * @export
 * @interface TrainingRequest
 */
export interface TrainingRequest {
    /**
     * 
     * @type {string}
     * @memberof TrainingRequest
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof TrainingRequest
     */
    organization_id: string;
    /**
     * 
     * @type {string}
     * @memberof TrainingRequest
     */
    submitted_by_user_id: string;
    /**
     * 
     * @type {string}
     * @memberof TrainingRequest
     */
    assigned_user_id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TrainingRequest
     */
    product_id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TrainingRequest
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof TrainingRequest
     */
    message: string;
    /**
     * 
     * @type {TrainingRequestStatus}
     * @memberof TrainingRequest
     */
    status: TrainingRequestStatus;
    /**
     * 
     * @type {Date}
     * @memberof TrainingRequest
     */
    scheduled_start_at?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof TrainingRequest
     */
    scheduled_end_at?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof TrainingRequest
     */
    date_added: Date;
    /**
     * 
     * @type {Date}
     * @memberof TrainingRequest
     */
    date_updated?: Date | null;
}



/**
 * Check if a given object implements the TrainingRequest interface.
 */
export function instanceOfTrainingRequest(value: object): value is TrainingRequest {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('organization_id' in value) || value['organization_id'] === undefined) return false;
    if (!('submitted_by_user_id' in value) || value['submitted_by_user_id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('date_added' in value) || value['date_added'] === undefined) return false;
    return true;
}

export function TrainingRequestFromJSON(json: any): TrainingRequest {
    return TrainingRequestFromJSONTyped(json, false);
}

export function TrainingRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrainingRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'organization_id': json['organization_id'],
        'submitted_by_user_id': json['submitted_by_user_id'],
        'assigned_user_id': json['assigned_user_id'] == null ? undefined : json['assigned_user_id'],
        'product_id': json['product_id'] == null ? undefined : json['product_id'],
        'title': json['title'],
        'message': json['message'],
        'status': TrainingRequestStatusFromJSON(json['status']),
        'scheduled_start_at': json['scheduled_start_at'] == null ? undefined : (new Date(json['scheduled_start_at'])),
        'scheduled_end_at': json['scheduled_end_at'] == null ? undefined : (new Date(json['scheduled_end_at'])),
        'date_added': (new Date(json['date_added'])),
        'date_updated': json['date_updated'] == null ? undefined : (new Date(json['date_updated'])),
    };
}

export function TrainingRequestToJSON(json: any): TrainingRequest {
    return TrainingRequestToJSONTyped(json, false);
}

export function TrainingRequestToJSONTyped(value?: TrainingRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'organization_id': value['organization_id'],
        'submitted_by_user_id': value['submitted_by_user_id'],
        'assigned_user_id': value['assigned_user_id'],
        'product_id': value['product_id'],
        'title': value['title'],
        'message': value['message'],
        'status': TrainingRequestStatusToJSON(value['status']),
        'scheduled_start_at': value['scheduled_start_at'] == null ? value['scheduled_start_at'] : value['scheduled_start_at'].toISOString(),
        'scheduled_end_at': value['scheduled_end_at'] == null ? value['scheduled_end_at'] : value['scheduled_end_at'].toISOString(),
        'date_added': value['date_added'].toISOString(),
        'date_updated': value['date_updated'] == null ? value['date_updated'] : value['date_updated'].toISOString(),
    };
}

