/* tslint:disable */
/* eslint-disable */
/**
 * MedBridge API
 * MedBridge backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TrainingRequestStatus } from './TrainingRequestStatus';
import {
    TrainingRequestStatusFromJSON,
    TrainingRequestStatusFromJSONTyped,
    TrainingRequestStatusToJSON,
    TrainingRequestStatusToJSONTyped,
} from './TrainingRequestStatus';

/**
 * 
 * @export
 * @interface TrainingRequest
 */
export interface TrainingRequest {
    /**
     * 
     * @type {string}
     * @memberof TrainingRequest
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof TrainingRequest
     */
    requester_user_id: string;
    /**
     * 
     * @type {string}
     * @memberof TrainingRequest
     */
    hospital_organization_id: string;
    /**
     * 
     * @type {string}
     * @memberof TrainingRequest
     */
    product_id?: string | null;
    /**
     * 
     * @type {TrainingRequestStatus}
     * @memberof TrainingRequest
     */
    status: TrainingRequestStatus;
    /**
     * 
     * @type {string}
     * @memberof TrainingRequest
     */
    topic?: string;
    /**
     * 
     * @type {string}
     * @memberof TrainingRequest
     */
    notes?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof TrainingRequest
     */
    created_at: Date;
    /**
     * 
     * @type {Date}
     * @memberof TrainingRequest
     */
    updated_at?: Date | null;
}



/**
 * Check if a given object implements the TrainingRequest interface.
 */
export function instanceOfTrainingRequest(value: object): value is TrainingRequest {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('requester_user_id' in value) || value['requester_user_id'] === undefined) return false;
    if (!('hospital_organization_id' in value) || value['hospital_organization_id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('created_at' in value) || value['created_at'] === undefined) return false;
    return true;
}

export function TrainingRequestFromJSON(json: any): TrainingRequest {
    return TrainingRequestFromJSONTyped(json, false);
}

export function TrainingRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrainingRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'requester_user_id': json['requester_user_id'],
        'hospital_organization_id': json['hospital_organization_id'],
        'product_id': json['product_id'] == null ? undefined : json['product_id'],
        'status': TrainingRequestStatusFromJSON(json['status']),
        'topic': json['topic'] == null ? undefined : json['topic'],
        'notes': json['notes'] == null ? undefined : json['notes'],
        'created_at': (new Date(json['created_at'])),
        'updated_at': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
    };
}

export function TrainingRequestToJSON(json: any): TrainingRequest {
    return TrainingRequestToJSONTyped(json, false);
}

export function TrainingRequestToJSONTyped(value?: TrainingRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'requester_user_id': value['requester_user_id'],
        'hospital_organization_id': value['hospital_organization_id'],
        'product_id': value['product_id'],
        'status': TrainingRequestStatusToJSON(value['status']),
        'topic': value['topic'],
        'notes': value['notes'],
        'created_at': value['created_at'].toISOString(),
        'updated_at': value['updated_at'] == null ? value['updated_at'] : value['updated_at'].toISOString(),
    };
}

