/* tslint:disable */
/* eslint-disable */
/**
 * DrawBridge API
 * DrawBridge backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CatalogContentType } from './CatalogContentType';
import {
    CatalogContentTypeFromJSON,
    CatalogContentTypeFromJSONTyped,
    CatalogContentTypeToJSON,
    CatalogContentTypeToJSONTyped,
} from './CatalogContentType';

/**
 * 
 * @export
 * @interface UpdateCatalogContentRequest
 */
export interface UpdateCatalogContentRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateCatalogContentRequest
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCatalogContentRequest
     */
    description?: string;
    /**
     * 
     * @type {CatalogContentType}
     * @memberof UpdateCatalogContentRequest
     */
    content_type?: CatalogContentType;
    /**
     * 
     * @type {string}
     * @memberof UpdateCatalogContentRequest
     */
    external_url?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdateCatalogContentRequest
     */
    tags?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof UpdateCatalogContentRequest
     */
    product_id?: string;
}



/**
 * Check if a given object implements the UpdateCatalogContentRequest interface.
 */
export function instanceOfUpdateCatalogContentRequest(value: object): value is UpdateCatalogContentRequest {
    return true;
}

export function UpdateCatalogContentRequestFromJSON(json: any): UpdateCatalogContentRequest {
    return UpdateCatalogContentRequestFromJSONTyped(json, false);
}

export function UpdateCatalogContentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateCatalogContentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'content_type': json['content_type'] == null ? undefined : CatalogContentTypeFromJSON(json['content_type']),
        'external_url': json['external_url'] == null ? undefined : json['external_url'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'product_id': json['product_id'] == null ? undefined : json['product_id'],
    };
}

export function UpdateCatalogContentRequestToJSON(json: any): UpdateCatalogContentRequest {
    return UpdateCatalogContentRequestToJSONTyped(json, false);
}

export function UpdateCatalogContentRequestToJSONTyped(value?: UpdateCatalogContentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'content_type': CatalogContentTypeToJSON(value['content_type']),
        'external_url': value['external_url'],
        'tags': value['tags'],
        'product_id': value['product_id'],
    };
}

