/* tslint:disable */
/* eslint-disable */
/**
 * DrawBridge API
 * DrawBridge backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserPersona } from './UserPersona';
import {
    UserPersonaFromJSON,
    UserPersonaFromJSONTyped,
    UserPersonaToJSON,
    UserPersonaToJSONTyped,
} from './UserPersona';

/**
 * 
 * @export
 * @interface UpdateAdminUserAuthorizationRequest
 */
export interface UpdateAdminUserAuthorizationRequest {
    /**
     * 
     * @type {UserPersona}
     * @memberof UpdateAdminUserAuthorizationRequest
     */
    persona: UserPersona;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdateAdminUserAuthorizationRequest
     */
    grant_permissions: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdateAdminUserAuthorizationRequest
     */
    deny_permissions: Array<string>;
}



/**
 * Check if a given object implements the UpdateAdminUserAuthorizationRequest interface.
 */
export function instanceOfUpdateAdminUserAuthorizationRequest(value: object): value is UpdateAdminUserAuthorizationRequest {
    if (!('persona' in value) || value['persona'] === undefined) return false;
    if (!('grant_permissions' in value) || value['grant_permissions'] === undefined) return false;
    if (!('deny_permissions' in value) || value['deny_permissions'] === undefined) return false;
    return true;
}

export function UpdateAdminUserAuthorizationRequestFromJSON(json: any): UpdateAdminUserAuthorizationRequest {
    return UpdateAdminUserAuthorizationRequestFromJSONTyped(json, false);
}

export function UpdateAdminUserAuthorizationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateAdminUserAuthorizationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'persona': UserPersonaFromJSON(json['persona']),
        'grant_permissions': json['grant_permissions'],
        'deny_permissions': json['deny_permissions'],
    };
}

export function UpdateAdminUserAuthorizationRequestToJSON(json: any): UpdateAdminUserAuthorizationRequest {
    return UpdateAdminUserAuthorizationRequestToJSONTyped(json, false);
}

export function UpdateAdminUserAuthorizationRequestToJSONTyped(value?: UpdateAdminUserAuthorizationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'persona': UserPersonaToJSON(value['persona']),
        'grant_permissions': value['grant_permissions'],
        'deny_permissions': value['deny_permissions'],
    };
}

