/* tslint:disable */
/* eslint-disable */
/**
 * DrawBridge API
 * DrawBridge backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RepAvailabilityStatus } from './RepAvailabilityStatus';
import {
    RepAvailabilityStatusFromJSON,
    RepAvailabilityStatusFromJSONTyped,
    RepAvailabilityStatusToJSON,
    RepAvailabilityStatusToJSONTyped,
} from './RepAvailabilityStatus';
import type { RepAvailabilityWindowType } from './RepAvailabilityWindowType';
import {
    RepAvailabilityWindowTypeFromJSON,
    RepAvailabilityWindowTypeFromJSONTyped,
    RepAvailabilityWindowTypeToJSON,
    RepAvailabilityWindowTypeToJSONTyped,
} from './RepAvailabilityWindowType';

/**
 * 
 * @export
 * @interface UpsertRepAvailabilityWindowRequest
 */
export interface UpsertRepAvailabilityWindowRequest {
    /**
     * 
     * @type {RepAvailabilityWindowType}
     * @memberof UpsertRepAvailabilityWindowRequest
     */
    window_type: RepAvailabilityWindowType;
    /**
     * 
     * @type {Date}
     * @memberof UpsertRepAvailabilityWindowRequest
     */
    starts_at?: Date;
    /**
     * 
     * @type {Date}
     * @memberof UpsertRepAvailabilityWindowRequest
     */
    ends_at?: Date;
    /**
     * 
     * @type {number}
     * @memberof UpsertRepAvailabilityWindowRequest
     */
    weekday?: number;
    /**
     * 
     * @type {number}
     * @memberof UpsertRepAvailabilityWindowRequest
     */
    start_minute?: number;
    /**
     * 
     * @type {number}
     * @memberof UpsertRepAvailabilityWindowRequest
     */
    end_minute?: number;
    /**
     * 
     * @type {Date}
     * @memberof UpsertRepAvailabilityWindowRequest
     */
    effective_from?: Date;
    /**
     * 
     * @type {Date}
     * @memberof UpsertRepAvailabilityWindowRequest
     */
    effective_until?: Date;
    /**
     * 
     * @type {RepAvailabilityStatus}
     * @memberof UpsertRepAvailabilityWindowRequest
     */
    status: RepAvailabilityStatus;
    /**
     * 
     * @type {string}
     * @memberof UpsertRepAvailabilityWindowRequest
     */
    note?: string;
}



/**
 * Check if a given object implements the UpsertRepAvailabilityWindowRequest interface.
 */
export function instanceOfUpsertRepAvailabilityWindowRequest(value: object): value is UpsertRepAvailabilityWindowRequest {
    if (!('window_type' in value) || value['window_type'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function UpsertRepAvailabilityWindowRequestFromJSON(json: any): UpsertRepAvailabilityWindowRequest {
    return UpsertRepAvailabilityWindowRequestFromJSONTyped(json, false);
}

export function UpsertRepAvailabilityWindowRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpsertRepAvailabilityWindowRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'window_type': RepAvailabilityWindowTypeFromJSON(json['window_type']),
        'starts_at': json['starts_at'] == null ? undefined : (new Date(json['starts_at'])),
        'ends_at': json['ends_at'] == null ? undefined : (new Date(json['ends_at'])),
        'weekday': json['weekday'] == null ? undefined : json['weekday'],
        'start_minute': json['start_minute'] == null ? undefined : json['start_minute'],
        'end_minute': json['end_minute'] == null ? undefined : json['end_minute'],
        'effective_from': json['effective_from'] == null ? undefined : (new Date(json['effective_from'])),
        'effective_until': json['effective_until'] == null ? undefined : (new Date(json['effective_until'])),
        'status': RepAvailabilityStatusFromJSON(json['status']),
        'note': json['note'] == null ? undefined : json['note'],
    };
}

export function UpsertRepAvailabilityWindowRequestToJSON(json: any): UpsertRepAvailabilityWindowRequest {
    return UpsertRepAvailabilityWindowRequestToJSONTyped(json, false);
}

export function UpsertRepAvailabilityWindowRequestToJSONTyped(value?: UpsertRepAvailabilityWindowRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'window_type': RepAvailabilityWindowTypeToJSON(value['window_type']),
        'starts_at': value['starts_at'] == null ? value['starts_at'] : value['starts_at'].toISOString(),
        'ends_at': value['ends_at'] == null ? value['ends_at'] : value['ends_at'].toISOString(),
        'weekday': value['weekday'],
        'start_minute': value['start_minute'],
        'end_minute': value['end_minute'],
        'effective_from': value['effective_from'] == null ? value['effective_from'] : value['effective_from'].toISOString().substring(0,10),
        'effective_until': value['effective_until'] == null ? value['effective_until'] : value['effective_until'].toISOString().substring(0,10),
        'status': RepAvailabilityStatusToJSON(value['status']),
        'note': value['note'],
    };
}

