/* tslint:disable */
/* eslint-disable */
/**
 * MedBridge API
 * MedBridge backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const UserPersona = {
    User: 'user',
    Representative: 'representative'
} as const;
export type UserPersona = typeof UserPersona[keyof typeof UserPersona];


export function instanceOfUserPersona(value: any): boolean {
    for (const key in UserPersona) {
        if (Object.prototype.hasOwnProperty.call(UserPersona, key)) {
            if (UserPersona[key as keyof typeof UserPersona] === value) {
                return true;
            }
        }
    }
    return false;
}

export function UserPersonaFromJSON(json: any): UserPersona {
    return UserPersonaFromJSONTyped(json, false);
}

export function UserPersonaFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserPersona {
    return json as UserPersona;
}

export function UserPersonaToJSON(value?: UserPersona | null): any {
    return value as any;
}

export function UserPersonaToJSONTyped(value: any, ignoreDiscriminator: boolean): UserPersona {
    return value as UserPersona;
}

