/* tslint:disable */
/* eslint-disable */
/**
 * MedBridge API
 * MedBridge backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserProduct
 */
export interface UserProduct {
    /**
     * 
     * @type {string}
     * @memberof UserProduct
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof UserProduct
     */
    user_id: string;
    /**
     * 
     * @type {string}
     * @memberof UserProduct
     */
    product_id: string;
    /**
     * 
     * @type {Date}
     * @memberof UserProduct
     */
    date_added: Date;
}

/**
 * Check if a given object implements the UserProduct interface.
 */
export function instanceOfUserProduct(value: object): value is UserProduct {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('user_id' in value) || value['user_id'] === undefined) return false;
    if (!('product_id' in value) || value['product_id'] === undefined) return false;
    if (!('date_added' in value) || value['date_added'] === undefined) return false;
    return true;
}

export function UserProductFromJSON(json: any): UserProduct {
    return UserProductFromJSONTyped(json, false);
}

export function UserProductFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserProduct {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'user_id': json['user_id'],
        'product_id': json['product_id'],
        'date_added': (new Date(json['date_added'])),
    };
}

export function UserProductToJSON(json: any): UserProduct {
    return UserProductToJSONTyped(json, false);
}

export function UserProductToJSONTyped(value?: UserProduct | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'user_id': value['user_id'],
        'product_id': value['product_id'],
        'date_added': value['date_added'].toISOString(),
    };
}

