/* tslint:disable */
/* eslint-disable */
/**
 * MedBridge API
 * MedBridge backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VideoPlayResponse
 */
export interface VideoPlayResponse {
    /**
     * 
     * @type {string}
     * @memberof VideoPlayResponse
     */
    playback_url: string;
    /**
     * 
     * @type {Date}
     * @memberof VideoPlayResponse
     */
    expires_at: Date;
}

/**
 * Check if a given object implements the VideoPlayResponse interface.
 */
export function instanceOfVideoPlayResponse(value: object): value is VideoPlayResponse {
    if (!('playback_url' in value) || value['playback_url'] === undefined) return false;
    if (!('expires_at' in value) || value['expires_at'] === undefined) return false;
    return true;
}

export function VideoPlayResponseFromJSON(json: any): VideoPlayResponse {
    return VideoPlayResponseFromJSONTyped(json, false);
}

export function VideoPlayResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VideoPlayResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'playback_url': json['playback_url'],
        'expires_at': (new Date(json['expires_at'])),
    };
}

export function VideoPlayResponseToJSON(json: any): VideoPlayResponse {
    return VideoPlayResponseToJSONTyped(json, false);
}

export function VideoPlayResponseToJSONTyped(value?: VideoPlayResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'playback_url': value['playback_url'],
        'expires_at': value['expires_at'].toISOString(),
    };
}

