/* tslint:disable */
/* eslint-disable */
/**
 * MedBridge API
 * MedBridge backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VideoStatus } from './VideoStatus';
import {
    VideoStatusFromJSON,
    VideoStatusFromJSONTyped,
    VideoStatusToJSON,
    VideoStatusToJSONTyped,
} from './VideoStatus';

/**
 * 
 * @export
 * @interface Video
 */
export interface Video {
    /**
     * 
     * @type {string}
     * @memberof Video
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Video
     */
    organization_id: string;
    /**
     * 
     * @type {string}
     * @memberof Video
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof Video
     */
    description?: string | null;
    /**
     * 
     * @type {VideoStatus}
     * @memberof Video
     */
    status: VideoStatus;
    /**
     * 
     * @type {number}
     * @memberof Video
     */
    duration_seconds?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof Video
     */
    created_at: Date;
    /**
     * 
     * @type {Date}
     * @memberof Video
     */
    updated_at?: Date | null;
}



/**
 * Check if a given object implements the Video interface.
 */
export function instanceOfVideo(value: object): value is Video {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('organization_id' in value) || value['organization_id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('created_at' in value) || value['created_at'] === undefined) return false;
    return true;
}

export function VideoFromJSON(json: any): Video {
    return VideoFromJSONTyped(json, false);
}

export function VideoFromJSONTyped(json: any, ignoreDiscriminator: boolean): Video {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'organization_id': json['organization_id'],
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'status': VideoStatusFromJSON(json['status']),
        'duration_seconds': json['duration_seconds'] == null ? undefined : json['duration_seconds'],
        'created_at': (new Date(json['created_at'])),
        'updated_at': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
    };
}

export function VideoToJSON(json: any): Video {
    return VideoToJSONTyped(json, false);
}

export function VideoToJSONTyped(value?: Video | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'organization_id': value['organization_id'],
        'title': value['title'],
        'description': value['description'],
        'status': VideoStatusToJSON(value['status']),
        'duration_seconds': value['duration_seconds'],
        'created_at': value['created_at'].toISOString(),
        'updated_at': value['updated_at'] == null ? value['updated_at'] : value['updated_at'].toISOString(),
    };
}

