/* tslint:disable */
/* eslint-disable */
/**
 * MedBridge API
 * MedBridge backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const VideoStatus = {
    Draft: 'draft',
    Uploaded: 'uploaded',
    Processing: 'processing',
    Ready: 'ready',
    Failed: 'failed'
} as const;
export type VideoStatus = typeof VideoStatus[keyof typeof VideoStatus];


export function instanceOfVideoStatus(value: any): boolean {
    for (const key in VideoStatus) {
        if (Object.prototype.hasOwnProperty.call(VideoStatus, key)) {
            if (VideoStatus[key as keyof typeof VideoStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function VideoStatusFromJSON(json: any): VideoStatus {
    return VideoStatusFromJSONTyped(json, false);
}

export function VideoStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): VideoStatus {
    return json as VideoStatus;
}

export function VideoStatusToJSON(value?: VideoStatus | null): any {
    return value as any;
}

export function VideoStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): VideoStatus {
    return value as VideoStatus;
}

