/* tslint:disable */
/* eslint-disable */
/**
 * DrawBridge API
 * DrawBridge backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebinarIceServer
 */
export interface WebinarIceServer {
    /**
     * 
     * @type {Array<string>}
     * @memberof WebinarIceServer
     */
    urls: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof WebinarIceServer
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof WebinarIceServer
     */
    credential?: string;
}

/**
 * Check if a given object implements the WebinarIceServer interface.
 */
export function instanceOfWebinarIceServer(value: object): value is WebinarIceServer {
    if (!('urls' in value) || value['urls'] === undefined) return false;
    return true;
}

export function WebinarIceServerFromJSON(json: any): WebinarIceServer {
    return WebinarIceServerFromJSONTyped(json, false);
}

export function WebinarIceServerFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebinarIceServer {
    if (json == null) {
        return json;
    }
    return {
        
        'urls': json['urls'],
        'username': json['username'] == null ? undefined : json['username'],
        'credential': json['credential'] == null ? undefined : json['credential'],
    };
}

export function WebinarIceServerToJSON(json: any): WebinarIceServer {
    return WebinarIceServerToJSONTyped(json, false);
}

export function WebinarIceServerToJSONTyped(value?: WebinarIceServer | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'urls': value['urls'],
        'username': value['username'],
        'credential': value['credential'],
    };
}

