/* tslint:disable */
/* eslint-disable */
/**
 * DrawBridge API
 * DrawBridge backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WebinarQnAStatus } from './WebinarQnAStatus';
import {
    WebinarQnAStatusFromJSON,
    WebinarQnAStatusFromJSONTyped,
    WebinarQnAStatusToJSON,
    WebinarQnAStatusToJSONTyped,
} from './WebinarQnAStatus';

/**
 * 
 * @export
 * @interface WebinarQnAItem
 */
export interface WebinarQnAItem {
    /**
     * 
     * @type {string}
     * @memberof WebinarQnAItem
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof WebinarQnAItem
     */
    webinar_id: string;
    /**
     * 
     * @type {string}
     * @memberof WebinarQnAItem
     */
    asked_by_user_id: string;
    /**
     * 
     * @type {string}
     * @memberof WebinarQnAItem
     */
    question: string;
    /**
     * 
     * @type {string}
     * @memberof WebinarQnAItem
     */
    answer?: string;
    /**
     * 
     * @type {string}
     * @memberof WebinarQnAItem
     */
    answered_by_user_id?: string | null;
    /**
     * 
     * @type {WebinarQnAStatus}
     * @memberof WebinarQnAItem
     */
    status: WebinarQnAStatus;
    /**
     * 
     * @type {Date}
     * @memberof WebinarQnAItem
     */
    answered_at?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof WebinarQnAItem
     */
    date_added: Date;
    /**
     * 
     * @type {Date}
     * @memberof WebinarQnAItem
     */
    date_updated?: Date | null;
}



/**
 * Check if a given object implements the WebinarQnAItem interface.
 */
export function instanceOfWebinarQnAItem(value: object): value is WebinarQnAItem {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('webinar_id' in value) || value['webinar_id'] === undefined) return false;
    if (!('asked_by_user_id' in value) || value['asked_by_user_id'] === undefined) return false;
    if (!('question' in value) || value['question'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('date_added' in value) || value['date_added'] === undefined) return false;
    return true;
}

export function WebinarQnAItemFromJSON(json: any): WebinarQnAItem {
    return WebinarQnAItemFromJSONTyped(json, false);
}

export function WebinarQnAItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebinarQnAItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'webinar_id': json['webinar_id'],
        'asked_by_user_id': json['asked_by_user_id'],
        'question': json['question'],
        'answer': json['answer'] == null ? undefined : json['answer'],
        'answered_by_user_id': json['answered_by_user_id'] == null ? undefined : json['answered_by_user_id'],
        'status': WebinarQnAStatusFromJSON(json['status']),
        'answered_at': json['answered_at'] == null ? undefined : (new Date(json['answered_at'])),
        'date_added': (new Date(json['date_added'])),
        'date_updated': json['date_updated'] == null ? undefined : (new Date(json['date_updated'])),
    };
}

export function WebinarQnAItemToJSON(json: any): WebinarQnAItem {
    return WebinarQnAItemToJSONTyped(json, false);
}

export function WebinarQnAItemToJSONTyped(value?: WebinarQnAItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'webinar_id': value['webinar_id'],
        'asked_by_user_id': value['asked_by_user_id'],
        'question': value['question'],
        'answer': value['answer'],
        'answered_by_user_id': value['answered_by_user_id'],
        'status': WebinarQnAStatusToJSON(value['status']),
        'answered_at': value['answered_at'] == null ? value['answered_at'] : value['answered_at'].toISOString(),
        'date_added': value['date_added'].toISOString(),
        'date_updated': value['date_updated'] == null ? value['date_updated'] : value['date_updated'].toISOString(),
    };
}

