/* tslint:disable */
/* eslint-disable */
/**
 * DrawBridge API
 * DrawBridge backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const WebinarStatus = {
    Scheduled: 'scheduled',
    Live: 'live',
    Ended: 'ended',
    Cancelled: 'cancelled'
} as const;
export type WebinarStatus = typeof WebinarStatus[keyof typeof WebinarStatus];


export function instanceOfWebinarStatus(value: any): boolean {
    for (const key in WebinarStatus) {
        if (Object.prototype.hasOwnProperty.call(WebinarStatus, key)) {
            if (WebinarStatus[key as keyof typeof WebinarStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function WebinarStatusFromJSON(json: any): WebinarStatus {
    return WebinarStatusFromJSONTyped(json, false);
}

export function WebinarStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebinarStatus {
    return json as WebinarStatus;
}

export function WebinarStatusToJSON(value?: WebinarStatus | null): any {
    return value as any;
}

export function WebinarStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): WebinarStatus {
    return value as WebinarStatus;
}

