/* tslint:disable */
/* eslint-disable */
/**
 * DrawBridge API
 * DrawBridge backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const WebinarQnAStatus = {
    Open: 'open',
    Approved: 'approved',
    Answered: 'answered',
    Dismissed: 'dismissed'
} as const;
export type WebinarQnAStatus = typeof WebinarQnAStatus[keyof typeof WebinarQnAStatus];


export function instanceOfWebinarQnAStatus(value: any): boolean {
    for (const key in WebinarQnAStatus) {
        if (Object.prototype.hasOwnProperty.call(WebinarQnAStatus, key)) {
            if (WebinarQnAStatus[key as keyof typeof WebinarQnAStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function WebinarQnAStatusFromJSON(json: any): WebinarQnAStatus {
    return WebinarQnAStatusFromJSONTyped(json, false);
}

export function WebinarQnAStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebinarQnAStatus {
    return json as WebinarQnAStatus;
}

export function WebinarQnAStatusToJSON(value?: WebinarQnAStatus | null): any {
    return value as any;
}

export function WebinarQnAStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): WebinarQnAStatus {
    return value as WebinarQnAStatus;
}

