/* tslint:disable */
/* eslint-disable */
/**
 * DrawBridge API
 * DrawBridge backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebinarJoinResult
 */
export interface WebinarJoinResult {
    /**
     * 
     * @type {string}
     * @memberof WebinarJoinResult
     */
    participant_token: string;
    /**
     * 
     * @type {Date}
     * @memberof WebinarJoinResult
     */
    expires_at: Date;
    /**
     * 
     * @type {string}
     * @memberof WebinarJoinResult
     */
    signal_path: string;
    /**
     * 
     * @type {string}
     * @memberof WebinarJoinResult
     */
    room_owner_node: string;
}

/**
 * Check if a given object implements the WebinarJoinResult interface.
 */
export function instanceOfWebinarJoinResult(value: object): value is WebinarJoinResult {
    if (!('participant_token' in value) || value['participant_token'] === undefined) return false;
    if (!('expires_at' in value) || value['expires_at'] === undefined) return false;
    if (!('signal_path' in value) || value['signal_path'] === undefined) return false;
    if (!('room_owner_node' in value) || value['room_owner_node'] === undefined) return false;
    return true;
}

export function WebinarJoinResultFromJSON(json: any): WebinarJoinResult {
    return WebinarJoinResultFromJSONTyped(json, false);
}

export function WebinarJoinResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebinarJoinResult {
    if (json == null) {
        return json;
    }
    return {
        
        'participant_token': json['participant_token'],
        'expires_at': (new Date(json['expires_at'])),
        'signal_path': json['signal_path'],
        'room_owner_node': json['room_owner_node'],
    };
}

export function WebinarJoinResultToJSON(json: any): WebinarJoinResult {
    return WebinarJoinResultToJSONTyped(json, false);
}

export function WebinarJoinResultToJSONTyped(value?: WebinarJoinResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'participant_token': value['participant_token'],
        'expires_at': value['expires_at'].toISOString(),
        'signal_path': value['signal_path'],
        'room_owner_node': value['room_owner_node'],
    };
}

