/* tslint:disable */
/* eslint-disable */
/**
 * DrawBridge API
 * DrawBridge backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WebinarStatus } from './WebinarStatus';
import {
    WebinarStatusFromJSON,
    WebinarStatusFromJSONTyped,
    WebinarStatusToJSON,
    WebinarStatusToJSONTyped,
} from './WebinarStatus';

/**
 * 
 * @export
 * @interface Webinar
 */
export interface Webinar {
    /**
     * 
     * @type {string}
     * @memberof Webinar
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Webinar
     */
    organization_id: string;
    /**
     * 
     * @type {string}
     * @memberof Webinar
     */
    host_user_id: string;
    /**
     * 
     * @type {string}
     * @memberof Webinar
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof Webinar
     */
    description?: string;
    /**
     * 
     * @type {Date}
     * @memberof Webinar
     */
    starts_at: Date;
    /**
     * 
     * @type {Date}
     * @memberof Webinar
     */
    ends_at: Date;
    /**
     * 
     * @type {WebinarStatus}
     * @memberof Webinar
     */
    status: WebinarStatus;
    /**
     * 
     * @type {Date}
     * @memberof Webinar
     */
    started_at?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof Webinar
     */
    ended_at?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof Webinar
     */
    room_key: string;
    /**
     * 
     * @type {Date}
     * @memberof Webinar
     */
    date_added: Date;
    /**
     * 
     * @type {Date}
     * @memberof Webinar
     */
    date_updated?: Date | null;
}



/**
 * Check if a given object implements the Webinar interface.
 */
export function instanceOfWebinar(value: object): value is Webinar {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('organization_id' in value) || value['organization_id'] === undefined) return false;
    if (!('host_user_id' in value) || value['host_user_id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('starts_at' in value) || value['starts_at'] === undefined) return false;
    if (!('ends_at' in value) || value['ends_at'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('room_key' in value) || value['room_key'] === undefined) return false;
    if (!('date_added' in value) || value['date_added'] === undefined) return false;
    return true;
}

export function WebinarFromJSON(json: any): Webinar {
    return WebinarFromJSONTyped(json, false);
}

export function WebinarFromJSONTyped(json: any, ignoreDiscriminator: boolean): Webinar {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'organization_id': json['organization_id'],
        'host_user_id': json['host_user_id'],
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'starts_at': (new Date(json['starts_at'])),
        'ends_at': (new Date(json['ends_at'])),
        'status': WebinarStatusFromJSON(json['status']),
        'started_at': json['started_at'] == null ? undefined : (new Date(json['started_at'])),
        'ended_at': json['ended_at'] == null ? undefined : (new Date(json['ended_at'])),
        'room_key': json['room_key'],
        'date_added': (new Date(json['date_added'])),
        'date_updated': json['date_updated'] == null ? undefined : (new Date(json['date_updated'])),
    };
}

export function WebinarToJSON(json: any): Webinar {
    return WebinarToJSONTyped(json, false);
}

export function WebinarToJSONTyped(value?: Webinar | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'organization_id': value['organization_id'],
        'host_user_id': value['host_user_id'],
        'title': value['title'],
        'description': value['description'],
        'starts_at': value['starts_at'].toISOString(),
        'ends_at': value['ends_at'].toISOString(),
        'status': WebinarStatusToJSON(value['status']),
        'started_at': value['started_at'] == null ? value['started_at'] : value['started_at'].toISOString(),
        'ended_at': value['ended_at'] == null ? value['ended_at'] : value['ended_at'].toISOString(),
        'room_key': value['room_key'],
        'date_added': value['date_added'].toISOString(),
        'date_updated': value['date_updated'] == null ? value['date_updated'] : value['date_updated'].toISOString(),
    };
}

