/* tslint:disable */
/* eslint-disable */
/**
 * DrawBridge API
 * DrawBridge backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const WebinarParticipantRole = {
    Host: 'host',
    Cohost: 'cohost',
    Attendee: 'attendee'
} as const;
export type WebinarParticipantRole = typeof WebinarParticipantRole[keyof typeof WebinarParticipantRole];


export function instanceOfWebinarParticipantRole(value: any): boolean {
    for (const key in WebinarParticipantRole) {
        if (Object.prototype.hasOwnProperty.call(WebinarParticipantRole, key)) {
            if (WebinarParticipantRole[key as keyof typeof WebinarParticipantRole] === value) {
                return true;
            }
        }
    }
    return false;
}

export function WebinarParticipantRoleFromJSON(json: any): WebinarParticipantRole {
    return WebinarParticipantRoleFromJSONTyped(json, false);
}

export function WebinarParticipantRoleFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebinarParticipantRole {
    return json as WebinarParticipantRole;
}

export function WebinarParticipantRoleToJSON(value?: WebinarParticipantRole | null): any {
    return value as any;
}

export function WebinarParticipantRoleToJSONTyped(value: any, ignoreDiscriminator: boolean): WebinarParticipantRole {
    return value as WebinarParticipantRole;
}

