/* tslint:disable */
/* eslint-disable */
/**
 * DrawBridge API
 * DrawBridge backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateAdminUserRequest,
  ErrorResponse,
  User,
} from '../models/index';
import {
    CreateAdminUserRequestFromJSON,
    CreateAdminUserRequestToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    UserFromJSON,
    UserToJSON,
} from '../models/index';

export interface CreateAdminUserOperationRequest {
    createAdminUserRequest: CreateAdminUserRequest;
}

/**
 * AdminApi - interface
 * 
 * @export
 * @interface AdminApiInterface
 */
export interface AdminApiInterface {
    /**
     * Creates request options for createAdminUser without sending the request
     * @param {CreateAdminUserRequest} createAdminUserRequest 
     * @throws {RequiredError}
     * @memberof AdminApiInterface
     */
    createAdminUserRequestOpts(requestParameters: CreateAdminUserOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Create admin user
     * @param {CreateAdminUserRequest} createAdminUserRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminApiInterface
     */
    createAdminUserRaw(requestParameters: CreateAdminUserOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<User>>;

    /**
     * Create admin user
     */
    createAdminUser(requestParameters: CreateAdminUserOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<User>;

}

/**
 * 
 */
export class AdminApi extends runtime.BaseAPI implements AdminApiInterface {

    /**
     * Creates request options for createAdminUser without sending the request
     */
    async createAdminUserRequestOpts(requestParameters: CreateAdminUserOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createAdminUserRequest'] == null) {
            throw new runtime.RequiredError(
                'createAdminUserRequest',
                'Required parameter "createAdminUserRequest" was null or undefined when calling createAdminUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/admin/users`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateAdminUserRequestToJSON(requestParameters['createAdminUserRequest']),
        };
    }

    /**
     * Create admin user
     */
    async createAdminUserRaw(requestParameters: CreateAdminUserOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<User>> {
        const requestOptions = await this.createAdminUserRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserFromJSON(jsonValue));
    }

    /**
     * Create admin user
     */
    async createAdminUser(requestParameters: CreateAdminUserOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<User> {
        const response = await this.createAdminUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
