/* tslint:disable */
/* eslint-disable */
/**
 * DrawBridge API
 * DrawBridge backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CatalogContentItem,
  CreateCatalogContentRequest,
  ErrorResponse,
  UpdateCatalogContentRequest,
} from '../models/index';
import {
    CatalogContentItemFromJSON,
    CatalogContentItemToJSON,
    CreateCatalogContentRequestFromJSON,
    CreateCatalogContentRequestToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    UpdateCatalogContentRequestFromJSON,
    UpdateCatalogContentRequestToJSON,
} from '../models/index';

export interface CreateCatalogContentOperationRequest {
    createCatalogContentRequest: CreateCatalogContentRequest;
}

export interface DeleteCatalogContentRequest {
    id: string;
}

export interface GetCatalogContentRequest {
    id: string;
}

export interface ListCatalogContentRequest {
    q?: string;
    organizationId?: string;
    productId?: string;
    includeArchived?: boolean;
    types?: string;
    tags?: string;
}

export interface UpdateCatalogContentOperationRequest {
    id: string;
    updateCatalogContentRequest: UpdateCatalogContentRequest;
}

/**
 * CatalogApi - interface
 * 
 * @export
 * @interface CatalogApiInterface
 */
export interface CatalogApiInterface {
    /**
     * Creates request options for createCatalogContent without sending the request
     * @param {CreateCatalogContentRequest} createCatalogContentRequest 
     * @throws {RequiredError}
     * @memberof CatalogApiInterface
     */
    createCatalogContentRequestOpts(requestParameters: CreateCatalogContentOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Create catalog content
     * @param {CreateCatalogContentRequest} createCatalogContentRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CatalogApiInterface
     */
    createCatalogContentRaw(requestParameters: CreateCatalogContentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CatalogContentItem>>;

    /**
     * Create catalog content
     */
    createCatalogContent(requestParameters: CreateCatalogContentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CatalogContentItem>;

    /**
     * Creates request options for deleteCatalogContent without sending the request
     * @param {string} id 
     * @throws {RequiredError}
     * @memberof CatalogApiInterface
     */
    deleteCatalogContentRequestOpts(requestParameters: DeleteCatalogContentRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Archive catalog content
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CatalogApiInterface
     */
    deleteCatalogContentRaw(requestParameters: DeleteCatalogContentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Archive catalog content
     */
    deleteCatalogContent(requestParameters: DeleteCatalogContentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for getCatalogContent without sending the request
     * @param {string} id 
     * @throws {RequiredError}
     * @memberof CatalogApiInterface
     */
    getCatalogContentRequestOpts(requestParameters: GetCatalogContentRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Get catalog content
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CatalogApiInterface
     */
    getCatalogContentRaw(requestParameters: GetCatalogContentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CatalogContentItem>>;

    /**
     * Get catalog content
     */
    getCatalogContent(requestParameters: GetCatalogContentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CatalogContentItem>;

    /**
     * Creates request options for listCatalogContent without sending the request
     * @param {string} [q] 
     * @param {string} [organizationId] 
     * @param {string} [productId] 
     * @param {boolean} [includeArchived] 
     * @param {string} [types] Comma-separated content types
     * @param {string} [tags] Comma-separated content tags
     * @throws {RequiredError}
     * @memberof CatalogApiInterface
     */
    listCatalogContentRequestOpts(requestParameters: ListCatalogContentRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary List catalog content
     * @param {string} [q] 
     * @param {string} [organizationId] 
     * @param {string} [productId] 
     * @param {boolean} [includeArchived] 
     * @param {string} [types] Comma-separated content types
     * @param {string} [tags] Comma-separated content tags
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CatalogApiInterface
     */
    listCatalogContentRaw(requestParameters: ListCatalogContentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CatalogContentItem>>>;

    /**
     * List catalog content
     */
    listCatalogContent(requestParameters: ListCatalogContentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CatalogContentItem>>;

    /**
     * Creates request options for listCatalogContentTags without sending the request
     * @throws {RequiredError}
     * @memberof CatalogApiInterface
     */
    listCatalogContentTagsRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary List catalog content tags
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CatalogApiInterface
     */
    listCatalogContentTagsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string>>>;

    /**
     * List catalog content tags
     */
    listCatalogContentTags(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string>>;

    /**
     * Creates request options for updateCatalogContent without sending the request
     * @param {string} id 
     * @param {UpdateCatalogContentRequest} updateCatalogContentRequest 
     * @throws {RequiredError}
     * @memberof CatalogApiInterface
     */
    updateCatalogContentRequestOpts(requestParameters: UpdateCatalogContentOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Update catalog content
     * @param {string} id 
     * @param {UpdateCatalogContentRequest} updateCatalogContentRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CatalogApiInterface
     */
    updateCatalogContentRaw(requestParameters: UpdateCatalogContentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CatalogContentItem>>;

    /**
     * Update catalog content
     */
    updateCatalogContent(requestParameters: UpdateCatalogContentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CatalogContentItem>;

}

/**
 * 
 */
export class CatalogApi extends runtime.BaseAPI implements CatalogApiInterface {

    /**
     * Creates request options for createCatalogContent without sending the request
     */
    async createCatalogContentRequestOpts(requestParameters: CreateCatalogContentOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createCatalogContentRequest'] == null) {
            throw new runtime.RequiredError(
                'createCatalogContentRequest',
                'Required parameter "createCatalogContentRequest" was null or undefined when calling createCatalogContent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/catalog/content`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateCatalogContentRequestToJSON(requestParameters['createCatalogContentRequest']),
        };
    }

    /**
     * Create catalog content
     */
    async createCatalogContentRaw(requestParameters: CreateCatalogContentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CatalogContentItem>> {
        const requestOptions = await this.createCatalogContentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CatalogContentItemFromJSON(jsonValue));
    }

    /**
     * Create catalog content
     */
    async createCatalogContent(requestParameters: CreateCatalogContentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CatalogContentItem> {
        const response = await this.createCatalogContentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteCatalogContent without sending the request
     */
    async deleteCatalogContentRequestOpts(requestParameters: DeleteCatalogContentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteCatalogContent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/catalog/content/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Archive catalog content
     */
    async deleteCatalogContentRaw(requestParameters: DeleteCatalogContentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteCatalogContentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Archive catalog content
     */
    async deleteCatalogContent(requestParameters: DeleteCatalogContentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteCatalogContentRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getCatalogContent without sending the request
     */
    async getCatalogContentRequestOpts(requestParameters: GetCatalogContentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getCatalogContent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/catalog/content/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get catalog content
     */
    async getCatalogContentRaw(requestParameters: GetCatalogContentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CatalogContentItem>> {
        const requestOptions = await this.getCatalogContentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CatalogContentItemFromJSON(jsonValue));
    }

    /**
     * Get catalog content
     */
    async getCatalogContent(requestParameters: GetCatalogContentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CatalogContentItem> {
        const response = await this.getCatalogContentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listCatalogContent without sending the request
     */
    async listCatalogContentRequestOpts(requestParameters: ListCatalogContentRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        if (requestParameters['organizationId'] != null) {
            queryParameters['organization_id'] = requestParameters['organizationId'];
        }

        if (requestParameters['productId'] != null) {
            queryParameters['product_id'] = requestParameters['productId'];
        }

        if (requestParameters['includeArchived'] != null) {
            queryParameters['include_archived'] = requestParameters['includeArchived'];
        }

        if (requestParameters['types'] != null) {
            queryParameters['types'] = requestParameters['types'];
        }

        if (requestParameters['tags'] != null) {
            queryParameters['tags'] = requestParameters['tags'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/catalog/content`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List catalog content
     */
    async listCatalogContentRaw(requestParameters: ListCatalogContentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CatalogContentItem>>> {
        const requestOptions = await this.listCatalogContentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CatalogContentItemFromJSON));
    }

    /**
     * List catalog content
     */
    async listCatalogContent(requestParameters: ListCatalogContentRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CatalogContentItem>> {
        const response = await this.listCatalogContentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listCatalogContentTags without sending the request
     */
    async listCatalogContentTagsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/catalog/content/tags`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List catalog content tags
     */
    async listCatalogContentTagsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string>>> {
        const requestOptions = await this.listCatalogContentTagsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * List catalog content tags
     */
    async listCatalogContentTags(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string>> {
        const response = await this.listCatalogContentTagsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateCatalogContent without sending the request
     */
    async updateCatalogContentRequestOpts(requestParameters: UpdateCatalogContentOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateCatalogContent().'
            );
        }

        if (requestParameters['updateCatalogContentRequest'] == null) {
            throw new runtime.RequiredError(
                'updateCatalogContentRequest',
                'Required parameter "updateCatalogContentRequest" was null or undefined when calling updateCatalogContent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/catalog/content/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateCatalogContentRequestToJSON(requestParameters['updateCatalogContentRequest']),
        };
    }

    /**
     * Update catalog content
     */
    async updateCatalogContentRaw(requestParameters: UpdateCatalogContentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CatalogContentItem>> {
        const requestOptions = await this.updateCatalogContentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CatalogContentItemFromJSON(jsonValue));
    }

    /**
     * Update catalog content
     */
    async updateCatalogContent(requestParameters: UpdateCatalogContentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CatalogContentItem> {
        const response = await this.updateCatalogContentRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
