/* tslint:disable */
/* eslint-disable */
/**
 * MedBridge API
 * MedBridge backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateMembershipRequest,
  ErrorResponse,
  ListMembershipsResponse,
  Membership,
  MembershipStatus,
} from '../models/index';
import {
    CreateMembershipRequestFromJSON,
    CreateMembershipRequestToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    ListMembershipsResponseFromJSON,
    ListMembershipsResponseToJSON,
    MembershipFromJSON,
    MembershipToJSON,
    MembershipStatusFromJSON,
    MembershipStatusToJSON,
} from '../models/index';

export interface CreateOrganizationMembershipRequest {
    organizationId: string;
    createMembershipRequest: CreateMembershipRequest;
}

export interface ListOrganizationMembershipsRequest {
    organizationId: string;
    membershipStatus?: MembershipStatus;
}

/**
 * MembershipsApi - interface
 * 
 * @export
 * @interface MembershipsApiInterface
 */
export interface MembershipsApiInterface {
    /**
     * Creates request options for createOrganizationMembership without sending the request
     * @param {string} organizationId 
     * @param {CreateMembershipRequest} createMembershipRequest 
     * @throws {RequiredError}
     * @memberof MembershipsApiInterface
     */
    createOrganizationMembershipRequestOpts(requestParameters: CreateOrganizationMembershipRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Add organization membership
     * @param {string} organizationId 
     * @param {CreateMembershipRequest} createMembershipRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MembershipsApiInterface
     */
    createOrganizationMembershipRaw(requestParameters: CreateOrganizationMembershipRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Membership>>;

    /**
     * Add organization membership
     */
    createOrganizationMembership(requestParameters: CreateOrganizationMembershipRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Membership>;

    /**
     * Creates request options for listOrganizationMemberships without sending the request
     * @param {string} organizationId 
     * @param {MembershipStatus} [membershipStatus] 
     * @throws {RequiredError}
     * @memberof MembershipsApiInterface
     */
    listOrganizationMembershipsRequestOpts(requestParameters: ListOrganizationMembershipsRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary List organization memberships
     * @param {string} organizationId 
     * @param {MembershipStatus} [membershipStatus] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MembershipsApiInterface
     */
    listOrganizationMembershipsRaw(requestParameters: ListOrganizationMembershipsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListMembershipsResponse>>;

    /**
     * List organization memberships
     */
    listOrganizationMemberships(requestParameters: ListOrganizationMembershipsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListMembershipsResponse>;

}

/**
 * 
 */
export class MembershipsApi extends runtime.BaseAPI implements MembershipsApiInterface {

    /**
     * Creates request options for createOrganizationMembership without sending the request
     */
    async createOrganizationMembershipRequestOpts(requestParameters: CreateOrganizationMembershipRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['organizationId'] == null) {
            throw new runtime.RequiredError(
                'organizationId',
                'Required parameter "organizationId" was null or undefined when calling createOrganizationMembership().'
            );
        }

        if (requestParameters['createMembershipRequest'] == null) {
            throw new runtime.RequiredError(
                'createMembershipRequest',
                'Required parameter "createMembershipRequest" was null or undefined when calling createOrganizationMembership().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/organizations/{organizationId}/memberships`;
        urlPath = urlPath.replace(`{${"organizationId"}}`, encodeURIComponent(String(requestParameters['organizationId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateMembershipRequestToJSON(requestParameters['createMembershipRequest']),
        };
    }

    /**
     * Add organization membership
     */
    async createOrganizationMembershipRaw(requestParameters: CreateOrganizationMembershipRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Membership>> {
        const requestOptions = await this.createOrganizationMembershipRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MembershipFromJSON(jsonValue));
    }

    /**
     * Add organization membership
     */
    async createOrganizationMembership(requestParameters: CreateOrganizationMembershipRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Membership> {
        const response = await this.createOrganizationMembershipRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listOrganizationMemberships without sending the request
     */
    async listOrganizationMembershipsRequestOpts(requestParameters: ListOrganizationMembershipsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['organizationId'] == null) {
            throw new runtime.RequiredError(
                'organizationId',
                'Required parameter "organizationId" was null or undefined when calling listOrganizationMemberships().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['membershipStatus'] != null) {
            queryParameters['membership_status'] = requestParameters['membershipStatus'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/organizations/{organizationId}/memberships`;
        urlPath = urlPath.replace(`{${"organizationId"}}`, encodeURIComponent(String(requestParameters['organizationId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List organization memberships
     */
    async listOrganizationMembershipsRaw(requestParameters: ListOrganizationMembershipsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListMembershipsResponse>> {
        const requestOptions = await this.listOrganizationMembershipsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListMembershipsResponseFromJSON(jsonValue));
    }

    /**
     * List organization memberships
     */
    async listOrganizationMemberships(requestParameters: ListOrganizationMembershipsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListMembershipsResponse> {
        const response = await this.listOrganizationMembershipsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
