/* tslint:disable */
/* eslint-disable */
/**
 * MedBridge API
 * MedBridge backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateOrganizationRequest,
  ErrorResponse,
  ListOrganizationsResponse,
  OnboardingState,
  Organization,
  OrganizationType,
  PatchOrganizationRequest,
} from '../models/index';
import {
    CreateOrganizationRequestFromJSON,
    CreateOrganizationRequestToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    ListOrganizationsResponseFromJSON,
    ListOrganizationsResponseToJSON,
    OnboardingStateFromJSON,
    OnboardingStateToJSON,
    OrganizationFromJSON,
    OrganizationToJSON,
    OrganizationTypeFromJSON,
    OrganizationTypeToJSON,
    PatchOrganizationRequestFromJSON,
    PatchOrganizationRequestToJSON,
} from '../models/index';

export interface CreateOrganizationOperationRequest {
    createOrganizationRequest: CreateOrganizationRequest;
}

export interface GetOrganizationRequest {
    organizationId: string;
}

export interface ListOrganizationsRequest {
    orgType?: OrganizationType;
    onboardingState?: OnboardingState;
    page?: number;
    pageSize?: number;
}

export interface PatchOrganizationOperationRequest {
    organizationId: string;
    patchOrganizationRequest: PatchOrganizationRequest;
}

/**
 * OrganizationsApi - interface
 * 
 * @export
 * @interface OrganizationsApiInterface
 */
export interface OrganizationsApiInterface {
    /**
     * Creates request options for createOrganization without sending the request
     * @param {CreateOrganizationRequest} createOrganizationRequest 
     * @throws {RequiredError}
     * @memberof OrganizationsApiInterface
     */
    createOrganizationRequestOpts(requestParameters: CreateOrganizationOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Create organization
     * @param {CreateOrganizationRequest} createOrganizationRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OrganizationsApiInterface
     */
    createOrganizationRaw(requestParameters: CreateOrganizationOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Organization>>;

    /**
     * Create organization
     */
    createOrganization(requestParameters: CreateOrganizationOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Organization>;

    /**
     * Creates request options for getOrganization without sending the request
     * @param {string} organizationId 
     * @throws {RequiredError}
     * @memberof OrganizationsApiInterface
     */
    getOrganizationRequestOpts(requestParameters: GetOrganizationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Get organization
     * @param {string} organizationId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OrganizationsApiInterface
     */
    getOrganizationRaw(requestParameters: GetOrganizationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Organization>>;

    /**
     * Get organization
     */
    getOrganization(requestParameters: GetOrganizationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Organization>;

    /**
     * Creates request options for listOrganizations without sending the request
     * @param {OrganizationType} [orgType] 
     * @param {OnboardingState} [onboardingState] 
     * @param {number} [page] 
     * @param {number} [pageSize] 
     * @throws {RequiredError}
     * @memberof OrganizationsApiInterface
     */
    listOrganizationsRequestOpts(requestParameters: ListOrganizationsRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary List organizations
     * @param {OrganizationType} [orgType] 
     * @param {OnboardingState} [onboardingState] 
     * @param {number} [page] 
     * @param {number} [pageSize] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OrganizationsApiInterface
     */
    listOrganizationsRaw(requestParameters: ListOrganizationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListOrganizationsResponse>>;

    /**
     * List organizations
     */
    listOrganizations(requestParameters: ListOrganizationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListOrganizationsResponse>;

    /**
     * Creates request options for patchOrganization without sending the request
     * @param {string} organizationId 
     * @param {PatchOrganizationRequest} patchOrganizationRequest 
     * @throws {RequiredError}
     * @memberof OrganizationsApiInterface
     */
    patchOrganizationRequestOpts(requestParameters: PatchOrganizationOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Update organization
     * @param {string} organizationId 
     * @param {PatchOrganizationRequest} patchOrganizationRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OrganizationsApiInterface
     */
    patchOrganizationRaw(requestParameters: PatchOrganizationOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Organization>>;

    /**
     * Update organization
     */
    patchOrganization(requestParameters: PatchOrganizationOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Organization>;

}

/**
 * 
 */
export class OrganizationsApi extends runtime.BaseAPI implements OrganizationsApiInterface {

    /**
     * Creates request options for createOrganization without sending the request
     */
    async createOrganizationRequestOpts(requestParameters: CreateOrganizationOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createOrganizationRequest'] == null) {
            throw new runtime.RequiredError(
                'createOrganizationRequest',
                'Required parameter "createOrganizationRequest" was null or undefined when calling createOrganization().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/organizations`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateOrganizationRequestToJSON(requestParameters['createOrganizationRequest']),
        };
    }

    /**
     * Create organization
     */
    async createOrganizationRaw(requestParameters: CreateOrganizationOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Organization>> {
        const requestOptions = await this.createOrganizationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrganizationFromJSON(jsonValue));
    }

    /**
     * Create organization
     */
    async createOrganization(requestParameters: CreateOrganizationOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Organization> {
        const response = await this.createOrganizationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getOrganization without sending the request
     */
    async getOrganizationRequestOpts(requestParameters: GetOrganizationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['organizationId'] == null) {
            throw new runtime.RequiredError(
                'organizationId',
                'Required parameter "organizationId" was null or undefined when calling getOrganization().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/organizations/{organizationId}`;
        urlPath = urlPath.replace(`{${"organizationId"}}`, encodeURIComponent(String(requestParameters['organizationId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get organization
     */
    async getOrganizationRaw(requestParameters: GetOrganizationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Organization>> {
        const requestOptions = await this.getOrganizationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrganizationFromJSON(jsonValue));
    }

    /**
     * Get organization
     */
    async getOrganization(requestParameters: GetOrganizationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Organization> {
        const response = await this.getOrganizationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listOrganizations without sending the request
     */
    async listOrganizationsRequestOpts(requestParameters: ListOrganizationsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['orgType'] != null) {
            queryParameters['org_type'] = requestParameters['orgType'];
        }

        if (requestParameters['onboardingState'] != null) {
            queryParameters['onboarding_state'] = requestParameters['onboardingState'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['page_size'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/organizations`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List organizations
     */
    async listOrganizationsRaw(requestParameters: ListOrganizationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListOrganizationsResponse>> {
        const requestOptions = await this.listOrganizationsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListOrganizationsResponseFromJSON(jsonValue));
    }

    /**
     * List organizations
     */
    async listOrganizations(requestParameters: ListOrganizationsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListOrganizationsResponse> {
        const response = await this.listOrganizationsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for patchOrganization without sending the request
     */
    async patchOrganizationRequestOpts(requestParameters: PatchOrganizationOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['organizationId'] == null) {
            throw new runtime.RequiredError(
                'organizationId',
                'Required parameter "organizationId" was null or undefined when calling patchOrganization().'
            );
        }

        if (requestParameters['patchOrganizationRequest'] == null) {
            throw new runtime.RequiredError(
                'patchOrganizationRequest',
                'Required parameter "patchOrganizationRequest" was null or undefined when calling patchOrganization().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/organizations/{organizationId}`;
        urlPath = urlPath.replace(`{${"organizationId"}}`, encodeURIComponent(String(requestParameters['organizationId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PatchOrganizationRequestToJSON(requestParameters['patchOrganizationRequest']),
        };
    }

    /**
     * Update organization
     */
    async patchOrganizationRaw(requestParameters: PatchOrganizationOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Organization>> {
        const requestOptions = await this.patchOrganizationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrganizationFromJSON(jsonValue));
    }

    /**
     * Update organization
     */
    async patchOrganization(requestParameters: PatchOrganizationOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Organization> {
        const response = await this.patchOrganizationRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
