/* tslint:disable */
/* eslint-disable */
/**
 * DrawBridge API
 * DrawBridge backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateProductOrganizationRequest,
  CreateProductRequest,
  CreateProductUserRequest,
  ErrorResponse,
  Product,
  ProductOrganization,
  UserProduct,
} from '../models/index';
import {
    CreateProductOrganizationRequestFromJSON,
    CreateProductOrganizationRequestToJSON,
    CreateProductRequestFromJSON,
    CreateProductRequestToJSON,
    CreateProductUserRequestFromJSON,
    CreateProductUserRequestToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    ProductFromJSON,
    ProductToJSON,
    ProductOrganizationFromJSON,
    ProductOrganizationToJSON,
    UserProductFromJSON,
    UserProductToJSON,
} from '../models/index';

export interface CreateProductOperationRequest {
    createProductRequest: CreateProductRequest;
}

export interface CreateProductOrganizationOperationRequest {
    id: string;
    createProductOrganizationRequest: CreateProductOrganizationRequest;
}

export interface CreateProductUserOperationRequest {
    id: string;
    createProductUserRequest: CreateProductUserRequest;
}

export interface DeleteProductOrganizationRequest {
    id: string;
    organizationID: string;
}

export interface DeleteProductUserRequest {
    id: string;
    userID: string;
}

export interface GetProductRequest {
    id: string;
}

export interface ListProductOrganizationsRequest {
    id: string;
}

export interface ListProductUsersRequest {
    id: string;
}

export interface ListProductsRequest {
    scope?: ListProductsScopeEnum;
}

/**
 * ProductsApi - interface
 * 
 * @export
 * @interface ProductsApiInterface
 */
export interface ProductsApiInterface {
    /**
     * Creates request options for createProduct without sending the request
     * @param {CreateProductRequest} createProductRequest 
     * @throws {RequiredError}
     * @memberof ProductsApiInterface
     */
    createProductRequestOpts(requestParameters: CreateProductOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Create product
     * @param {CreateProductRequest} createProductRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProductsApiInterface
     */
    createProductRaw(requestParameters: CreateProductOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Product>>;

    /**
     * Create product
     */
    createProduct(requestParameters: CreateProductOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Product>;

    /**
     * Creates request options for createProductOrganization without sending the request
     * @param {string} id 
     * @param {CreateProductOrganizationRequest} createProductOrganizationRequest 
     * @throws {RequiredError}
     * @memberof ProductsApiInterface
     */
    createProductOrganizationRequestOpts(requestParameters: CreateProductOrganizationOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Add organization to product
     * @param {string} id 
     * @param {CreateProductOrganizationRequest} createProductOrganizationRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProductsApiInterface
     */
    createProductOrganizationRaw(requestParameters: CreateProductOrganizationOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProductOrganization>>;

    /**
     * Add organization to product
     */
    createProductOrganization(requestParameters: CreateProductOrganizationOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProductOrganization>;

    /**
     * Creates request options for createProductUser without sending the request
     * @param {string} id 
     * @param {CreateProductUserRequest} createProductUserRequest 
     * @throws {RequiredError}
     * @memberof ProductsApiInterface
     */
    createProductUserRequestOpts(requestParameters: CreateProductUserOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Add user to product
     * @param {string} id 
     * @param {CreateProductUserRequest} createProductUserRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProductsApiInterface
     */
    createProductUserRaw(requestParameters: CreateProductUserOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserProduct>>;

    /**
     * Add user to product
     */
    createProductUser(requestParameters: CreateProductUserOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserProduct>;

    /**
     * Creates request options for deleteProductOrganization without sending the request
     * @param {string} id 
     * @param {string} organizationID 
     * @throws {RequiredError}
     * @memberof ProductsApiInterface
     */
    deleteProductOrganizationRequestOpts(requestParameters: DeleteProductOrganizationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Remove organization from product
     * @param {string} id 
     * @param {string} organizationID 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProductsApiInterface
     */
    deleteProductOrganizationRaw(requestParameters: DeleteProductOrganizationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Remove organization from product
     */
    deleteProductOrganization(requestParameters: DeleteProductOrganizationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for deleteProductUser without sending the request
     * @param {string} id 
     * @param {string} userID 
     * @throws {RequiredError}
     * @memberof ProductsApiInterface
     */
    deleteProductUserRequestOpts(requestParameters: DeleteProductUserRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Remove user from product
     * @param {string} id 
     * @param {string} userID 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProductsApiInterface
     */
    deleteProductUserRaw(requestParameters: DeleteProductUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Remove user from product
     */
    deleteProductUser(requestParameters: DeleteProductUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for getProduct without sending the request
     * @param {string} id 
     * @throws {RequiredError}
     * @memberof ProductsApiInterface
     */
    getProductRequestOpts(requestParameters: GetProductRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Get product
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProductsApiInterface
     */
    getProductRaw(requestParameters: GetProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Product>>;

    /**
     * Get product
     */
    getProduct(requestParameters: GetProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Product>;

    /**
     * Creates request options for listProductOrganizations without sending the request
     * @param {string} id 
     * @throws {RequiredError}
     * @memberof ProductsApiInterface
     */
    listProductOrganizationsRequestOpts(requestParameters: ListProductOrganizationsRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary List product organizations
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProductsApiInterface
     */
    listProductOrganizationsRaw(requestParameters: ListProductOrganizationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ProductOrganization>>>;

    /**
     * List product organizations
     */
    listProductOrganizations(requestParameters: ListProductOrganizationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ProductOrganization>>;

    /**
     * Creates request options for listProductUsers without sending the request
     * @param {string} id 
     * @throws {RequiredError}
     * @memberof ProductsApiInterface
     */
    listProductUsersRequestOpts(requestParameters: ListProductUsersRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary List product users
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProductsApiInterface
     */
    listProductUsersRaw(requestParameters: ListProductUsersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<UserProduct>>>;

    /**
     * List product users
     */
    listProductUsers(requestParameters: ListProductUsersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<UserProduct>>;

    /**
     * Creates request options for listProducts without sending the request
     * @param {'assigned'} [scope] 
     * @throws {RequiredError}
     * @memberof ProductsApiInterface
     */
    listProductsRequestOpts(requestParameters: ListProductsRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary List products
     * @param {'assigned'} [scope] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProductsApiInterface
     */
    listProductsRaw(requestParameters: ListProductsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Product>>>;

    /**
     * List products
     */
    listProducts(requestParameters: ListProductsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Product>>;

}

/**
 * 
 */
export class ProductsApi extends runtime.BaseAPI implements ProductsApiInterface {

    /**
     * Creates request options for createProduct without sending the request
     */
    async createProductRequestOpts(requestParameters: CreateProductOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createProductRequest'] == null) {
            throw new runtime.RequiredError(
                'createProductRequest',
                'Required parameter "createProductRequest" was null or undefined when calling createProduct().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/products`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateProductRequestToJSON(requestParameters['createProductRequest']),
        };
    }

    /**
     * Create product
     */
    async createProductRaw(requestParameters: CreateProductOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Product>> {
        const requestOptions = await this.createProductRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProductFromJSON(jsonValue));
    }

    /**
     * Create product
     */
    async createProduct(requestParameters: CreateProductOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Product> {
        const response = await this.createProductRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createProductOrganization without sending the request
     */
    async createProductOrganizationRequestOpts(requestParameters: CreateProductOrganizationOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling createProductOrganization().'
            );
        }

        if (requestParameters['createProductOrganizationRequest'] == null) {
            throw new runtime.RequiredError(
                'createProductOrganizationRequest',
                'Required parameter "createProductOrganizationRequest" was null or undefined when calling createProductOrganization().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/products/{id}/organizations`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateProductOrganizationRequestToJSON(requestParameters['createProductOrganizationRequest']),
        };
    }

    /**
     * Add organization to product
     */
    async createProductOrganizationRaw(requestParameters: CreateProductOrganizationOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProductOrganization>> {
        const requestOptions = await this.createProductOrganizationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProductOrganizationFromJSON(jsonValue));
    }

    /**
     * Add organization to product
     */
    async createProductOrganization(requestParameters: CreateProductOrganizationOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProductOrganization> {
        const response = await this.createProductOrganizationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createProductUser without sending the request
     */
    async createProductUserRequestOpts(requestParameters: CreateProductUserOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling createProductUser().'
            );
        }

        if (requestParameters['createProductUserRequest'] == null) {
            throw new runtime.RequiredError(
                'createProductUserRequest',
                'Required parameter "createProductUserRequest" was null or undefined when calling createProductUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/products/{id}/users`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateProductUserRequestToJSON(requestParameters['createProductUserRequest']),
        };
    }

    /**
     * Add user to product
     */
    async createProductUserRaw(requestParameters: CreateProductUserOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserProduct>> {
        const requestOptions = await this.createProductUserRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserProductFromJSON(jsonValue));
    }

    /**
     * Add user to product
     */
    async createProductUser(requestParameters: CreateProductUserOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserProduct> {
        const response = await this.createProductUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteProductOrganization without sending the request
     */
    async deleteProductOrganizationRequestOpts(requestParameters: DeleteProductOrganizationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteProductOrganization().'
            );
        }

        if (requestParameters['organizationID'] == null) {
            throw new runtime.RequiredError(
                'organizationID',
                'Required parameter "organizationID" was null or undefined when calling deleteProductOrganization().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/products/{id}/organizations/{organizationID}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace(`{${"organizationID"}}`, encodeURIComponent(String(requestParameters['organizationID'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Remove organization from product
     */
    async deleteProductOrganizationRaw(requestParameters: DeleteProductOrganizationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteProductOrganizationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Remove organization from product
     */
    async deleteProductOrganization(requestParameters: DeleteProductOrganizationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteProductOrganizationRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for deleteProductUser without sending the request
     */
    async deleteProductUserRequestOpts(requestParameters: DeleteProductUserRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteProductUser().'
            );
        }

        if (requestParameters['userID'] == null) {
            throw new runtime.RequiredError(
                'userID',
                'Required parameter "userID" was null or undefined when calling deleteProductUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/products/{id}/users/{userID}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace(`{${"userID"}}`, encodeURIComponent(String(requestParameters['userID'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Remove user from product
     */
    async deleteProductUserRaw(requestParameters: DeleteProductUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteProductUserRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Remove user from product
     */
    async deleteProductUser(requestParameters: DeleteProductUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteProductUserRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getProduct without sending the request
     */
    async getProductRequestOpts(requestParameters: GetProductRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getProduct().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/products/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get product
     */
    async getProductRaw(requestParameters: GetProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Product>> {
        const requestOptions = await this.getProductRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProductFromJSON(jsonValue));
    }

    /**
     * Get product
     */
    async getProduct(requestParameters: GetProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Product> {
        const response = await this.getProductRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listProductOrganizations without sending the request
     */
    async listProductOrganizationsRequestOpts(requestParameters: ListProductOrganizationsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling listProductOrganizations().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/products/{id}/organizations`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List product organizations
     */
    async listProductOrganizationsRaw(requestParameters: ListProductOrganizationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ProductOrganization>>> {
        const requestOptions = await this.listProductOrganizationsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ProductOrganizationFromJSON));
    }

    /**
     * List product organizations
     */
    async listProductOrganizations(requestParameters: ListProductOrganizationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ProductOrganization>> {
        const response = await this.listProductOrganizationsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listProductUsers without sending the request
     */
    async listProductUsersRequestOpts(requestParameters: ListProductUsersRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling listProductUsers().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/products/{id}/users`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List product users
     */
    async listProductUsersRaw(requestParameters: ListProductUsersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<UserProduct>>> {
        const requestOptions = await this.listProductUsersRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(UserProductFromJSON));
    }

    /**
     * List product users
     */
    async listProductUsers(requestParameters: ListProductUsersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<UserProduct>> {
        const response = await this.listProductUsersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listProducts without sending the request
     */
    async listProductsRequestOpts(requestParameters: ListProductsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['scope'] != null) {
            queryParameters['scope'] = requestParameters['scope'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/products`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List products
     */
    async listProductsRaw(requestParameters: ListProductsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Product>>> {
        const requestOptions = await this.listProductsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ProductFromJSON));
    }

    /**
     * List products
     */
    async listProducts(requestParameters: ListProductsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Product>> {
        const response = await this.listProductsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const ListProductsScopeEnum = {
    Assigned: 'assigned'
} as const;
export type ListProductsScopeEnum = typeof ListProductsScopeEnum[keyof typeof ListProductsScopeEnum];
