/* tslint:disable */
/* eslint-disable */
/**
 * MedBridge API
 * MedBridge backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateProductRequest,
  ErrorResponse,
  ListProductsResponse,
  PatchProductRequest,
  Product,
} from '../models/index';
import {
    CreateProductRequestFromJSON,
    CreateProductRequestToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    ListProductsResponseFromJSON,
    ListProductsResponseToJSON,
    PatchProductRequestFromJSON,
    PatchProductRequestToJSON,
    ProductFromJSON,
    ProductToJSON,
} from '../models/index';

export interface CreateProductOperationRequest {
    createProductRequest: CreateProductRequest;
}

export interface DeleteHospitalProductRequest {
    hospitalId: string;
    productId: string;
}

export interface GetProductRequest {
    productId: string;
}

export interface ListProductsRequest {
    vendorOrganizationId?: string;
    page?: number;
    pageSize?: number;
}

export interface PatchProductOperationRequest {
    productId: string;
    patchProductRequest: PatchProductRequest;
}

export interface PutHospitalProductRequest {
    hospitalId: string;
    productId: string;
}

/**
 * ProductsApi - interface
 * 
 * @export
 * @interface ProductsApiInterface
 */
export interface ProductsApiInterface {
    /**
     * Creates request options for createProduct without sending the request
     * @param {CreateProductRequest} createProductRequest 
     * @throws {RequiredError}
     * @memberof ProductsApiInterface
     */
    createProductRequestOpts(requestParameters: CreateProductOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Create product
     * @param {CreateProductRequest} createProductRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProductsApiInterface
     */
    createProductRaw(requestParameters: CreateProductOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Product>>;

    /**
     * Create product
     */
    createProduct(requestParameters: CreateProductOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Product>;

    /**
     * Creates request options for deleteHospitalProduct without sending the request
     * @param {string} hospitalId 
     * @param {string} productId 
     * @throws {RequiredError}
     * @memberof ProductsApiInterface
     */
    deleteHospitalProductRequestOpts(requestParameters: DeleteHospitalProductRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Unlink product from hospital
     * @param {string} hospitalId 
     * @param {string} productId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProductsApiInterface
     */
    deleteHospitalProductRaw(requestParameters: DeleteHospitalProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Unlink product from hospital
     */
    deleteHospitalProduct(requestParameters: DeleteHospitalProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for getProduct without sending the request
     * @param {string} productId 
     * @throws {RequiredError}
     * @memberof ProductsApiInterface
     */
    getProductRequestOpts(requestParameters: GetProductRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Get product
     * @param {string} productId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProductsApiInterface
     */
    getProductRaw(requestParameters: GetProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Product>>;

    /**
     * Get product
     */
    getProduct(requestParameters: GetProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Product>;

    /**
     * Creates request options for listProducts without sending the request
     * @param {string} [vendorOrganizationId] 
     * @param {number} [page] 
     * @param {number} [pageSize] 
     * @throws {RequiredError}
     * @memberof ProductsApiInterface
     */
    listProductsRequestOpts(requestParameters: ListProductsRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary List products
     * @param {string} [vendorOrganizationId] 
     * @param {number} [page] 
     * @param {number} [pageSize] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProductsApiInterface
     */
    listProductsRaw(requestParameters: ListProductsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListProductsResponse>>;

    /**
     * List products
     */
    listProducts(requestParameters: ListProductsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListProductsResponse>;

    /**
     * Creates request options for patchProduct without sending the request
     * @param {string} productId 
     * @param {PatchProductRequest} patchProductRequest 
     * @throws {RequiredError}
     * @memberof ProductsApiInterface
     */
    patchProductRequestOpts(requestParameters: PatchProductOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Update product
     * @param {string} productId 
     * @param {PatchProductRequest} patchProductRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProductsApiInterface
     */
    patchProductRaw(requestParameters: PatchProductOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Product>>;

    /**
     * Update product
     */
    patchProduct(requestParameters: PatchProductOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Product>;

    /**
     * Creates request options for putHospitalProduct without sending the request
     * @param {string} hospitalId 
     * @param {string} productId 
     * @throws {RequiredError}
     * @memberof ProductsApiInterface
     */
    putHospitalProductRequestOpts(requestParameters: PutHospitalProductRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Link product to hospital
     * @param {string} hospitalId 
     * @param {string} productId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProductsApiInterface
     */
    putHospitalProductRaw(requestParameters: PutHospitalProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Link product to hospital
     */
    putHospitalProduct(requestParameters: PutHospitalProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

}

/**
 * 
 */
export class ProductsApi extends runtime.BaseAPI implements ProductsApiInterface {

    /**
     * Creates request options for createProduct without sending the request
     */
    async createProductRequestOpts(requestParameters: CreateProductOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createProductRequest'] == null) {
            throw new runtime.RequiredError(
                'createProductRequest',
                'Required parameter "createProductRequest" was null or undefined when calling createProduct().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/products`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateProductRequestToJSON(requestParameters['createProductRequest']),
        };
    }

    /**
     * Create product
     */
    async createProductRaw(requestParameters: CreateProductOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Product>> {
        const requestOptions = await this.createProductRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProductFromJSON(jsonValue));
    }

    /**
     * Create product
     */
    async createProduct(requestParameters: CreateProductOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Product> {
        const response = await this.createProductRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteHospitalProduct without sending the request
     */
    async deleteHospitalProductRequestOpts(requestParameters: DeleteHospitalProductRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['hospitalId'] == null) {
            throw new runtime.RequiredError(
                'hospitalId',
                'Required parameter "hospitalId" was null or undefined when calling deleteHospitalProduct().'
            );
        }

        if (requestParameters['productId'] == null) {
            throw new runtime.RequiredError(
                'productId',
                'Required parameter "productId" was null or undefined when calling deleteHospitalProduct().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/hospitals/{hospitalId}/products/{productId}`;
        urlPath = urlPath.replace(`{${"hospitalId"}}`, encodeURIComponent(String(requestParameters['hospitalId'])));
        urlPath = urlPath.replace(`{${"productId"}}`, encodeURIComponent(String(requestParameters['productId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Unlink product from hospital
     */
    async deleteHospitalProductRaw(requestParameters: DeleteHospitalProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteHospitalProductRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Unlink product from hospital
     */
    async deleteHospitalProduct(requestParameters: DeleteHospitalProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteHospitalProductRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getProduct without sending the request
     */
    async getProductRequestOpts(requestParameters: GetProductRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['productId'] == null) {
            throw new runtime.RequiredError(
                'productId',
                'Required parameter "productId" was null or undefined when calling getProduct().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/products/{productId}`;
        urlPath = urlPath.replace(`{${"productId"}}`, encodeURIComponent(String(requestParameters['productId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get product
     */
    async getProductRaw(requestParameters: GetProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Product>> {
        const requestOptions = await this.getProductRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProductFromJSON(jsonValue));
    }

    /**
     * Get product
     */
    async getProduct(requestParameters: GetProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Product> {
        const response = await this.getProductRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listProducts without sending the request
     */
    async listProductsRequestOpts(requestParameters: ListProductsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['vendorOrganizationId'] != null) {
            queryParameters['vendor_organization_id'] = requestParameters['vendorOrganizationId'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['page_size'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/products`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List products
     */
    async listProductsRaw(requestParameters: ListProductsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListProductsResponse>> {
        const requestOptions = await this.listProductsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListProductsResponseFromJSON(jsonValue));
    }

    /**
     * List products
     */
    async listProducts(requestParameters: ListProductsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListProductsResponse> {
        const response = await this.listProductsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for patchProduct without sending the request
     */
    async patchProductRequestOpts(requestParameters: PatchProductOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['productId'] == null) {
            throw new runtime.RequiredError(
                'productId',
                'Required parameter "productId" was null or undefined when calling patchProduct().'
            );
        }

        if (requestParameters['patchProductRequest'] == null) {
            throw new runtime.RequiredError(
                'patchProductRequest',
                'Required parameter "patchProductRequest" was null or undefined when calling patchProduct().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/products/{productId}`;
        urlPath = urlPath.replace(`{${"productId"}}`, encodeURIComponent(String(requestParameters['productId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PatchProductRequestToJSON(requestParameters['patchProductRequest']),
        };
    }

    /**
     * Update product
     */
    async patchProductRaw(requestParameters: PatchProductOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Product>> {
        const requestOptions = await this.patchProductRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProductFromJSON(jsonValue));
    }

    /**
     * Update product
     */
    async patchProduct(requestParameters: PatchProductOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Product> {
        const response = await this.patchProductRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for putHospitalProduct without sending the request
     */
    async putHospitalProductRequestOpts(requestParameters: PutHospitalProductRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['hospitalId'] == null) {
            throw new runtime.RequiredError(
                'hospitalId',
                'Required parameter "hospitalId" was null or undefined when calling putHospitalProduct().'
            );
        }

        if (requestParameters['productId'] == null) {
            throw new runtime.RequiredError(
                'productId',
                'Required parameter "productId" was null or undefined when calling putHospitalProduct().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/hospitals/{hospitalId}/products/{productId}`;
        urlPath = urlPath.replace(`{${"hospitalId"}}`, encodeURIComponent(String(requestParameters['hospitalId'])));
        urlPath = urlPath.replace(`{${"productId"}}`, encodeURIComponent(String(requestParameters['productId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Link product to hospital
     */
    async putHospitalProductRaw(requestParameters: PutHospitalProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.putHospitalProductRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Link product to hospital
     */
    async putHospitalProduct(requestParameters: PutHospitalProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.putHospitalProductRaw(requestParameters, initOverrides);
    }

}
