/* tslint:disable */
/* eslint-disable */
/**
 * MedBridge API
 * MedBridge backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CoverageStatus,
  CreateRepCoverageRequest,
  ErrorResponse,
  ListRepCoveragesResponse,
  RepCoverage,
} from '../models/index';
import {
    CoverageStatusFromJSON,
    CoverageStatusToJSON,
    CreateRepCoverageRequestFromJSON,
    CreateRepCoverageRequestToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    ListRepCoveragesResponseFromJSON,
    ListRepCoveragesResponseToJSON,
    RepCoverageFromJSON,
    RepCoverageToJSON,
} from '../models/index';

export interface CreateRepCoverageOperationRequest {
    createRepCoverageRequest: CreateRepCoverageRequest;
}

export interface ListRepCoveragesRequest {
    repUserId?: string;
    hospitalId?: string;
    status?: CoverageStatus;
}

/**
 * RepCoverageApi - interface
 * 
 * @export
 * @interface RepCoverageApiInterface
 */
export interface RepCoverageApiInterface {
    /**
     * Creates request options for createRepCoverage without sending the request
     * @param {CreateRepCoverageRequest} createRepCoverageRequest 
     * @throws {RequiredError}
     * @memberof RepCoverageApiInterface
     */
    createRepCoverageRequestOpts(requestParameters: CreateRepCoverageOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Create rep coverage
     * @param {CreateRepCoverageRequest} createRepCoverageRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RepCoverageApiInterface
     */
    createRepCoverageRaw(requestParameters: CreateRepCoverageOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RepCoverage>>;

    /**
     * Create rep coverage
     */
    createRepCoverage(requestParameters: CreateRepCoverageOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RepCoverage>;

    /**
     * Creates request options for listRepCoverages without sending the request
     * @param {string} [repUserId] 
     * @param {string} [hospitalId] 
     * @param {CoverageStatus} [status] 
     * @throws {RequiredError}
     * @memberof RepCoverageApiInterface
     */
    listRepCoveragesRequestOpts(requestParameters: ListRepCoveragesRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary List rep coverages
     * @param {string} [repUserId] 
     * @param {string} [hospitalId] 
     * @param {CoverageStatus} [status] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RepCoverageApiInterface
     */
    listRepCoveragesRaw(requestParameters: ListRepCoveragesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListRepCoveragesResponse>>;

    /**
     * List rep coverages
     */
    listRepCoverages(requestParameters: ListRepCoveragesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListRepCoveragesResponse>;

}

/**
 * 
 */
export class RepCoverageApi extends runtime.BaseAPI implements RepCoverageApiInterface {

    /**
     * Creates request options for createRepCoverage without sending the request
     */
    async createRepCoverageRequestOpts(requestParameters: CreateRepCoverageOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createRepCoverageRequest'] == null) {
            throw new runtime.RequiredError(
                'createRepCoverageRequest',
                'Required parameter "createRepCoverageRequest" was null or undefined when calling createRepCoverage().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/rep-coverages`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateRepCoverageRequestToJSON(requestParameters['createRepCoverageRequest']),
        };
    }

    /**
     * Create rep coverage
     */
    async createRepCoverageRaw(requestParameters: CreateRepCoverageOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RepCoverage>> {
        const requestOptions = await this.createRepCoverageRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RepCoverageFromJSON(jsonValue));
    }

    /**
     * Create rep coverage
     */
    async createRepCoverage(requestParameters: CreateRepCoverageOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RepCoverage> {
        const response = await this.createRepCoverageRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listRepCoverages without sending the request
     */
    async listRepCoveragesRequestOpts(requestParameters: ListRepCoveragesRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['repUserId'] != null) {
            queryParameters['rep_user_id'] = requestParameters['repUserId'];
        }

        if (requestParameters['hospitalId'] != null) {
            queryParameters['hospital_id'] = requestParameters['hospitalId'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/rep-coverages`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List rep coverages
     */
    async listRepCoveragesRaw(requestParameters: ListRepCoveragesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListRepCoveragesResponse>> {
        const requestOptions = await this.listRepCoveragesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListRepCoveragesResponseFromJSON(jsonValue));
    }

    /**
     * List rep coverages
     */
    async listRepCoverages(requestParameters: ListRepCoveragesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListRepCoveragesResponse> {
        const response = await this.listRepCoveragesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
