/* tslint:disable */
/* eslint-disable */
/**
 * MedBridge API
 * MedBridge backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateTrainingRequestRequest,
  ErrorResponse,
  ListTrainingRequestsResponse,
  PatchTrainingRequestRequest,
  TrainingRequest,
  TrainingRequestStatus,
} from '../models/index';
import {
    CreateTrainingRequestRequestFromJSON,
    CreateTrainingRequestRequestToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    ListTrainingRequestsResponseFromJSON,
    ListTrainingRequestsResponseToJSON,
    PatchTrainingRequestRequestFromJSON,
    PatchTrainingRequestRequestToJSON,
    TrainingRequestFromJSON,
    TrainingRequestToJSON,
    TrainingRequestStatusFromJSON,
    TrainingRequestStatusToJSON,
} from '../models/index';

export interface CreateTrainingRequestOperationRequest {
    createTrainingRequestRequest: CreateTrainingRequestRequest;
}

export interface GetTrainingRequestRequest {
    trainingRequestId: string;
}

export interface ListTrainingRequestsRequest {
    status?: TrainingRequestStatus;
    hospitalId?: string;
    productId?: string;
    page?: number;
    pageSize?: number;
}

export interface PatchTrainingRequestOperationRequest {
    trainingRequestId: string;
    patchTrainingRequestRequest: PatchTrainingRequestRequest;
}

/**
 * TrainingRequestsApi - interface
 * 
 * @export
 * @interface TrainingRequestsApiInterface
 */
export interface TrainingRequestsApiInterface {
    /**
     * Creates request options for createTrainingRequest without sending the request
     * @param {CreateTrainingRequestRequest} createTrainingRequestRequest 
     * @throws {RequiredError}
     * @memberof TrainingRequestsApiInterface
     */
    createTrainingRequestRequestOpts(requestParameters: CreateTrainingRequestOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Create training request
     * @param {CreateTrainingRequestRequest} createTrainingRequestRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TrainingRequestsApiInterface
     */
    createTrainingRequestRaw(requestParameters: CreateTrainingRequestOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TrainingRequest>>;

    /**
     * Create training request
     */
    createTrainingRequest(requestParameters: CreateTrainingRequestOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TrainingRequest>;

    /**
     * Creates request options for getTrainingRequest without sending the request
     * @param {string} trainingRequestId 
     * @throws {RequiredError}
     * @memberof TrainingRequestsApiInterface
     */
    getTrainingRequestRequestOpts(requestParameters: GetTrainingRequestRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Get training request
     * @param {string} trainingRequestId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TrainingRequestsApiInterface
     */
    getTrainingRequestRaw(requestParameters: GetTrainingRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TrainingRequest>>;

    /**
     * Get training request
     */
    getTrainingRequest(requestParameters: GetTrainingRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TrainingRequest>;

    /**
     * Creates request options for listTrainingRequests without sending the request
     * @param {TrainingRequestStatus} [status] 
     * @param {string} [hospitalId] 
     * @param {string} [productId] 
     * @param {number} [page] 
     * @param {number} [pageSize] 
     * @throws {RequiredError}
     * @memberof TrainingRequestsApiInterface
     */
    listTrainingRequestsRequestOpts(requestParameters: ListTrainingRequestsRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary List training requests
     * @param {TrainingRequestStatus} [status] 
     * @param {string} [hospitalId] 
     * @param {string} [productId] 
     * @param {number} [page] 
     * @param {number} [pageSize] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TrainingRequestsApiInterface
     */
    listTrainingRequestsRaw(requestParameters: ListTrainingRequestsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListTrainingRequestsResponse>>;

    /**
     * List training requests
     */
    listTrainingRequests(requestParameters: ListTrainingRequestsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListTrainingRequestsResponse>;

    /**
     * Creates request options for patchTrainingRequest without sending the request
     * @param {string} trainingRequestId 
     * @param {PatchTrainingRequestRequest} patchTrainingRequestRequest 
     * @throws {RequiredError}
     * @memberof TrainingRequestsApiInterface
     */
    patchTrainingRequestRequestOpts(requestParameters: PatchTrainingRequestOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Update training request status
     * @param {string} trainingRequestId 
     * @param {PatchTrainingRequestRequest} patchTrainingRequestRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TrainingRequestsApiInterface
     */
    patchTrainingRequestRaw(requestParameters: PatchTrainingRequestOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TrainingRequest>>;

    /**
     * Update training request status
     */
    patchTrainingRequest(requestParameters: PatchTrainingRequestOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TrainingRequest>;

}

/**
 * 
 */
export class TrainingRequestsApi extends runtime.BaseAPI implements TrainingRequestsApiInterface {

    /**
     * Creates request options for createTrainingRequest without sending the request
     */
    async createTrainingRequestRequestOpts(requestParameters: CreateTrainingRequestOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createTrainingRequestRequest'] == null) {
            throw new runtime.RequiredError(
                'createTrainingRequestRequest',
                'Required parameter "createTrainingRequestRequest" was null or undefined when calling createTrainingRequest().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/training-requests`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateTrainingRequestRequestToJSON(requestParameters['createTrainingRequestRequest']),
        };
    }

    /**
     * Create training request
     */
    async createTrainingRequestRaw(requestParameters: CreateTrainingRequestOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TrainingRequest>> {
        const requestOptions = await this.createTrainingRequestRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TrainingRequestFromJSON(jsonValue));
    }

    /**
     * Create training request
     */
    async createTrainingRequest(requestParameters: CreateTrainingRequestOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TrainingRequest> {
        const response = await this.createTrainingRequestRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getTrainingRequest without sending the request
     */
    async getTrainingRequestRequestOpts(requestParameters: GetTrainingRequestRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['trainingRequestId'] == null) {
            throw new runtime.RequiredError(
                'trainingRequestId',
                'Required parameter "trainingRequestId" was null or undefined when calling getTrainingRequest().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/training-requests/{trainingRequestId}`;
        urlPath = urlPath.replace(`{${"trainingRequestId"}}`, encodeURIComponent(String(requestParameters['trainingRequestId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get training request
     */
    async getTrainingRequestRaw(requestParameters: GetTrainingRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TrainingRequest>> {
        const requestOptions = await this.getTrainingRequestRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TrainingRequestFromJSON(jsonValue));
    }

    /**
     * Get training request
     */
    async getTrainingRequest(requestParameters: GetTrainingRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TrainingRequest> {
        const response = await this.getTrainingRequestRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listTrainingRequests without sending the request
     */
    async listTrainingRequestsRequestOpts(requestParameters: ListTrainingRequestsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['hospitalId'] != null) {
            queryParameters['hospital_id'] = requestParameters['hospitalId'];
        }

        if (requestParameters['productId'] != null) {
            queryParameters['product_id'] = requestParameters['productId'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['page_size'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/training-requests`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List training requests
     */
    async listTrainingRequestsRaw(requestParameters: ListTrainingRequestsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListTrainingRequestsResponse>> {
        const requestOptions = await this.listTrainingRequestsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListTrainingRequestsResponseFromJSON(jsonValue));
    }

    /**
     * List training requests
     */
    async listTrainingRequests(requestParameters: ListTrainingRequestsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListTrainingRequestsResponse> {
        const response = await this.listTrainingRequestsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for patchTrainingRequest without sending the request
     */
    async patchTrainingRequestRequestOpts(requestParameters: PatchTrainingRequestOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['trainingRequestId'] == null) {
            throw new runtime.RequiredError(
                'trainingRequestId',
                'Required parameter "trainingRequestId" was null or undefined when calling patchTrainingRequest().'
            );
        }

        if (requestParameters['patchTrainingRequestRequest'] == null) {
            throw new runtime.RequiredError(
                'patchTrainingRequestRequest',
                'Required parameter "patchTrainingRequestRequest" was null or undefined when calling patchTrainingRequest().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/training-requests/{trainingRequestId}`;
        urlPath = urlPath.replace(`{${"trainingRequestId"}}`, encodeURIComponent(String(requestParameters['trainingRequestId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PatchTrainingRequestRequestToJSON(requestParameters['patchTrainingRequestRequest']),
        };
    }

    /**
     * Update training request status
     */
    async patchTrainingRequestRaw(requestParameters: PatchTrainingRequestOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TrainingRequest>> {
        const requestOptions = await this.patchTrainingRequestRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TrainingRequestFromJSON(jsonValue));
    }

    /**
     * Update training request status
     */
    async patchTrainingRequest(requestParameters: PatchTrainingRequestOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TrainingRequest> {
        const response = await this.patchTrainingRequestRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
