/* tslint:disable */
/* eslint-disable */
/**
 * DrawBridge API
 * DrawBridge backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateTrainingRequest,
  ErrorResponse,
  TrainingRequest,
  UpdateTrainingRequestStatusRequest,
} from '../models/index';
import {
    CreateTrainingRequestFromJSON,
    CreateTrainingRequestToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    TrainingRequestFromJSON,
    TrainingRequestToJSON,
    UpdateTrainingRequestStatusRequestFromJSON,
    UpdateTrainingRequestStatusRequestToJSON,
} from '../models/index';

export interface CreateTrainingRequestRequest {
    createTrainingRequest: CreateTrainingRequest;
}

export interface ListTrainingRequestsRequest {
    organizationId?: string;
    submittedByUserId?: string;
    assignedUserId?: string;
    statuses?: string;
}

export interface UpdateTrainingRequestStatusOperationRequest {
    id: string;
    updateTrainingRequestStatusRequest: UpdateTrainingRequestStatusRequest;
}

/**
 * TrainingApi - interface
 * 
 * @export
 * @interface TrainingApiInterface
 */
export interface TrainingApiInterface {
    /**
     * Creates request options for createTrainingRequest without sending the request
     * @param {CreateTrainingRequest} createTrainingRequest 
     * @throws {RequiredError}
     * @memberof TrainingApiInterface
     */
    createTrainingRequestRequestOpts(requestParameters: CreateTrainingRequestRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Create training request
     * @param {CreateTrainingRequest} createTrainingRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TrainingApiInterface
     */
    createTrainingRequestRaw(requestParameters: CreateTrainingRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TrainingRequest>>;

    /**
     * Create training request
     */
    createTrainingRequest(requestParameters: CreateTrainingRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TrainingRequest>;

    /**
     * Creates request options for listTrainingRequests without sending the request
     * @param {string} [organizationId] 
     * @param {string} [submittedByUserId] 
     * @param {string} [assignedUserId] 
     * @param {string} [statuses] Comma-separated training request statuses
     * @throws {RequiredError}
     * @memberof TrainingApiInterface
     */
    listTrainingRequestsRequestOpts(requestParameters: ListTrainingRequestsRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary List training requests
     * @param {string} [organizationId] 
     * @param {string} [submittedByUserId] 
     * @param {string} [assignedUserId] 
     * @param {string} [statuses] Comma-separated training request statuses
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TrainingApiInterface
     */
    listTrainingRequestsRaw(requestParameters: ListTrainingRequestsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TrainingRequest>>>;

    /**
     * List training requests
     */
    listTrainingRequests(requestParameters: ListTrainingRequestsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TrainingRequest>>;

    /**
     * Creates request options for updateTrainingRequestStatus without sending the request
     * @param {string} id 
     * @param {UpdateTrainingRequestStatusRequest} updateTrainingRequestStatusRequest 
     * @throws {RequiredError}
     * @memberof TrainingApiInterface
     */
    updateTrainingRequestStatusRequestOpts(requestParameters: UpdateTrainingRequestStatusOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Update training request status
     * @param {string} id 
     * @param {UpdateTrainingRequestStatusRequest} updateTrainingRequestStatusRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TrainingApiInterface
     */
    updateTrainingRequestStatusRaw(requestParameters: UpdateTrainingRequestStatusOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TrainingRequest>>;

    /**
     * Update training request status
     */
    updateTrainingRequestStatus(requestParameters: UpdateTrainingRequestStatusOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TrainingRequest>;

}

/**
 * 
 */
export class TrainingApi extends runtime.BaseAPI implements TrainingApiInterface {

    /**
     * Creates request options for createTrainingRequest without sending the request
     */
    async createTrainingRequestRequestOpts(requestParameters: CreateTrainingRequestRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createTrainingRequest'] == null) {
            throw new runtime.RequiredError(
                'createTrainingRequest',
                'Required parameter "createTrainingRequest" was null or undefined when calling createTrainingRequest().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/training/requests/`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateTrainingRequestToJSON(requestParameters['createTrainingRequest']),
        };
    }

    /**
     * Create training request
     */
    async createTrainingRequestRaw(requestParameters: CreateTrainingRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TrainingRequest>> {
        const requestOptions = await this.createTrainingRequestRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TrainingRequestFromJSON(jsonValue));
    }

    /**
     * Create training request
     */
    async createTrainingRequest(requestParameters: CreateTrainingRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TrainingRequest> {
        const response = await this.createTrainingRequestRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listTrainingRequests without sending the request
     */
    async listTrainingRequestsRequestOpts(requestParameters: ListTrainingRequestsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['organizationId'] != null) {
            queryParameters['organization_id'] = requestParameters['organizationId'];
        }

        if (requestParameters['submittedByUserId'] != null) {
            queryParameters['submitted_by_user_id'] = requestParameters['submittedByUserId'];
        }

        if (requestParameters['assignedUserId'] != null) {
            queryParameters['assigned_user_id'] = requestParameters['assignedUserId'];
        }

        if (requestParameters['statuses'] != null) {
            queryParameters['statuses'] = requestParameters['statuses'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/training/requests/`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List training requests
     */
    async listTrainingRequestsRaw(requestParameters: ListTrainingRequestsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TrainingRequest>>> {
        const requestOptions = await this.listTrainingRequestsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TrainingRequestFromJSON));
    }

    /**
     * List training requests
     */
    async listTrainingRequests(requestParameters: ListTrainingRequestsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TrainingRequest>> {
        const response = await this.listTrainingRequestsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateTrainingRequestStatus without sending the request
     */
    async updateTrainingRequestStatusRequestOpts(requestParameters: UpdateTrainingRequestStatusOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateTrainingRequestStatus().'
            );
        }

        if (requestParameters['updateTrainingRequestStatusRequest'] == null) {
            throw new runtime.RequiredError(
                'updateTrainingRequestStatusRequest',
                'Required parameter "updateTrainingRequestStatusRequest" was null or undefined when calling updateTrainingRequestStatus().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/training/requests/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateTrainingRequestStatusRequestToJSON(requestParameters['updateTrainingRequestStatusRequest']),
        };
    }

    /**
     * Update training request status
     */
    async updateTrainingRequestStatusRaw(requestParameters: UpdateTrainingRequestStatusOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TrainingRequest>> {
        const requestOptions = await this.updateTrainingRequestStatusRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TrainingRequestFromJSON(jsonValue));
    }

    /**
     * Update training request status
     */
    async updateTrainingRequestStatus(requestParameters: UpdateTrainingRequestStatusOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TrainingRequest> {
        const response = await this.updateTrainingRequestStatusRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
