/* tslint:disable */
/* eslint-disable */
/**
 * MedBridge API
 * MedBridge backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AcceptInviteRequest,
  ErrorResponse,
  User,
} from '../models/index';
import {
    AcceptInviteRequestFromJSON,
    AcceptInviteRequestToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    UserFromJSON,
    UserToJSON,
} from '../models/index';

export interface AcceptUserInviteRequest {
    acceptInviteRequest: AcceptInviteRequest;
}

export interface GetUserByIdRequest {
    id: string;
}

/**
 * UsersApi - interface
 * 
 * @export
 * @interface UsersApiInterface
 */
export interface UsersApiInterface {
    /**
     * Creates request options for acceptUserInvite without sending the request
     * @param {AcceptInviteRequest} acceptInviteRequest 
     * @throws {RequiredError}
     * @memberof UsersApiInterface
     */
    acceptUserInviteRequestOpts(requestParameters: AcceptUserInviteRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Accept invite and create credentials
     * @param {AcceptInviteRequest} acceptInviteRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApiInterface
     */
    acceptUserInviteRaw(requestParameters: AcceptUserInviteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<User>>;

    /**
     * Accept invite and create credentials
     */
    acceptUserInvite(requestParameters: AcceptUserInviteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<User>;

    /**
     * Creates request options for getUserById without sending the request
     * @param {string} id 
     * @throws {RequiredError}
     * @memberof UsersApiInterface
     */
    getUserByIdRequestOpts(requestParameters: GetUserByIdRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Get user by id
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApiInterface
     */
    getUserByIdRaw(requestParameters: GetUserByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<User>>;

    /**
     * Get user by id
     */
    getUserById(requestParameters: GetUserByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<User>;

}

/**
 * 
 */
export class UsersApi extends runtime.BaseAPI implements UsersApiInterface {

    /**
     * Creates request options for acceptUserInvite without sending the request
     */
    async acceptUserInviteRequestOpts(requestParameters: AcceptUserInviteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['acceptInviteRequest'] == null) {
            throw new runtime.RequiredError(
                'acceptInviteRequest',
                'Required parameter "acceptInviteRequest" was null or undefined when calling acceptUserInvite().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/users/invites/accept`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AcceptInviteRequestToJSON(requestParameters['acceptInviteRequest']),
        };
    }

    /**
     * Accept invite and create credentials
     */
    async acceptUserInviteRaw(requestParameters: AcceptUserInviteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<User>> {
        const requestOptions = await this.acceptUserInviteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserFromJSON(jsonValue));
    }

    /**
     * Accept invite and create credentials
     */
    async acceptUserInvite(requestParameters: AcceptUserInviteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<User> {
        const response = await this.acceptUserInviteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getUserById without sending the request
     */
    async getUserByIdRequestOpts(requestParameters: GetUserByIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getUserById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/users/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get user by id
     */
    async getUserByIdRaw(requestParameters: GetUserByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<User>> {
        const requestOptions = await this.getUserByIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserFromJSON(jsonValue));
    }

    /**
     * Get user by id
     */
    async getUserById(requestParameters: GetUserByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<User> {
        const response = await this.getUserByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
