/* tslint:disable */
/* eslint-disable */
/**
 * MedBridge API
 * MedBridge backend API specification.  HIPAA-safe guardrail: this API does not store or process PHI. No patient identity data, no case tracking, and no procedure schedules. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateVideoRequest,
  ErrorResponse,
  Video,
  VideoPlayResponse,
} from '../models/index';
import {
    CreateVideoRequestFromJSON,
    CreateVideoRequestToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    VideoFromJSON,
    VideoToJSON,
    VideoPlayResponseFromJSON,
    VideoPlayResponseToJSON,
} from '../models/index';

export interface CompleteVideoUploadRequest {
    videoId: string;
}

export interface CreateVideoOperationRequest {
    createVideoRequest: CreateVideoRequest;
}

export interface GetVideoRequest {
    videoId: string;
}

export interface GetVideoPlayRequest {
    videoId: string;
}

/**
 * VideosApi - interface
 * 
 * @export
 * @interface VideosApiInterface
 */
export interface VideosApiInterface {
    /**
     * Creates request options for completeVideoUpload without sending the request
     * @param {string} videoId 
     * @throws {RequiredError}
     * @memberof VideosApiInterface
     */
    completeVideoUploadRequestOpts(requestParameters: CompleteVideoUploadRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Mark upload complete
     * @param {string} videoId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VideosApiInterface
     */
    completeVideoUploadRaw(requestParameters: CompleteVideoUploadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Mark upload complete
     */
    completeVideoUpload(requestParameters: CompleteVideoUploadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for createVideo without sending the request
     * @param {CreateVideoRequest} createVideoRequest 
     * @throws {RequiredError}
     * @memberof VideosApiInterface
     */
    createVideoRequestOpts(requestParameters: CreateVideoOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Create video upload record
     * @param {CreateVideoRequest} createVideoRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VideosApiInterface
     */
    createVideoRaw(requestParameters: CreateVideoOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Video>>;

    /**
     * Create video upload record
     */
    createVideo(requestParameters: CreateVideoOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Video>;

    /**
     * Creates request options for getVideo without sending the request
     * @param {string} videoId 
     * @throws {RequiredError}
     * @memberof VideosApiInterface
     */
    getVideoRequestOpts(requestParameters: GetVideoRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Get video
     * @param {string} videoId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VideosApiInterface
     */
    getVideoRaw(requestParameters: GetVideoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Video>>;

    /**
     * Get video
     */
    getVideo(requestParameters: GetVideoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Video>;

    /**
     * Creates request options for getVideoPlay without sending the request
     * @param {string} videoId 
     * @throws {RequiredError}
     * @memberof VideosApiInterface
     */
    getVideoPlayRequestOpts(requestParameters: GetVideoPlayRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Get short-lived playback authorization
     * @param {string} videoId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VideosApiInterface
     */
    getVideoPlayRaw(requestParameters: GetVideoPlayRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VideoPlayResponse>>;

    /**
     * Get short-lived playback authorization
     */
    getVideoPlay(requestParameters: GetVideoPlayRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VideoPlayResponse>;

}

/**
 * 
 */
export class VideosApi extends runtime.BaseAPI implements VideosApiInterface {

    /**
     * Creates request options for completeVideoUpload without sending the request
     */
    async completeVideoUploadRequestOpts(requestParameters: CompleteVideoUploadRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['videoId'] == null) {
            throw new runtime.RequiredError(
                'videoId',
                'Required parameter "videoId" was null or undefined when calling completeVideoUpload().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/videos/{videoId}/upload-complete`;
        urlPath = urlPath.replace(`{${"videoId"}}`, encodeURIComponent(String(requestParameters['videoId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Mark upload complete
     */
    async completeVideoUploadRaw(requestParameters: CompleteVideoUploadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.completeVideoUploadRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Mark upload complete
     */
    async completeVideoUpload(requestParameters: CompleteVideoUploadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.completeVideoUploadRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for createVideo without sending the request
     */
    async createVideoRequestOpts(requestParameters: CreateVideoOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createVideoRequest'] == null) {
            throw new runtime.RequiredError(
                'createVideoRequest',
                'Required parameter "createVideoRequest" was null or undefined when calling createVideo().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/videos`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateVideoRequestToJSON(requestParameters['createVideoRequest']),
        };
    }

    /**
     * Create video upload record
     */
    async createVideoRaw(requestParameters: CreateVideoOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Video>> {
        const requestOptions = await this.createVideoRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VideoFromJSON(jsonValue));
    }

    /**
     * Create video upload record
     */
    async createVideo(requestParameters: CreateVideoOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Video> {
        const response = await this.createVideoRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getVideo without sending the request
     */
    async getVideoRequestOpts(requestParameters: GetVideoRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['videoId'] == null) {
            throw new runtime.RequiredError(
                'videoId',
                'Required parameter "videoId" was null or undefined when calling getVideo().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/videos/{videoId}`;
        urlPath = urlPath.replace(`{${"videoId"}}`, encodeURIComponent(String(requestParameters['videoId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get video
     */
    async getVideoRaw(requestParameters: GetVideoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Video>> {
        const requestOptions = await this.getVideoRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VideoFromJSON(jsonValue));
    }

    /**
     * Get video
     */
    async getVideo(requestParameters: GetVideoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Video> {
        const response = await this.getVideoRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getVideoPlay without sending the request
     */
    async getVideoPlayRequestOpts(requestParameters: GetVideoPlayRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['videoId'] == null) {
            throw new runtime.RequiredError(
                'videoId',
                'Required parameter "videoId" was null or undefined when calling getVideoPlay().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/videos/{videoId}/play`;
        urlPath = urlPath.replace(`{${"videoId"}}`, encodeURIComponent(String(requestParameters['videoId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get short-lived playback authorization
     */
    async getVideoPlayRaw(requestParameters: GetVideoPlayRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VideoPlayResponse>> {
        const requestOptions = await this.getVideoPlayRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VideoPlayResponseFromJSON(jsonValue));
    }

    /**
     * Get short-lived playback authorization
     */
    async getVideoPlay(requestParameters: GetVideoPlayRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VideoPlayResponse> {
        const response = await this.getVideoPlayRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
